- .github/stale.yaml
This workflow will check the PR and mark them as stale (adding the `stale` label) if no activity has been recorded on the PR for 14 days.
After that, if for another 21 days the PR is still stale, the PR will be close.
> [B2BP-26] Add stale workflow

- .infrastructure/06_alb.tf
Creation of Terraform scripts for the automatic deployment on AWS of resources necessary for Strapi.
Set port ALB Listener to 80 for communication with CloudFront:
FLOW:  Users ----HTTPS 443 ---> CloudFront-----HTTP 80 ---> ALB Listener ----forward HTTP---> TargetGroup ECS ----MappingPort 80:1337---> Container STRAPI
Set port ALB Listener to 80 for communication with CloudFront
Running Terraform scripts on locally PC pointing to a test AWS environment
> [B2BP-175] - Terraform set port ALB

- .infrastructure/03_network.tf
Creation of Terraform scripts for modify ALB Security Group, so that it is reachable only from CloudFront on HTTP:80
Creation of Terraform scripts for modify ALB Security Group, so that it is reachable only from CloudFront on HTTP:80
As reported in the [RFC "SV-003 - Architettura Strapi on AWS"](https://pagopa.atlassian.net/wiki/spaces/SV/pages/795771078/SV-003+-+Architettura+Strapi+on+AWS), to host the Strapi instance on the AWS Cloud Provider it is necessary to create the relevant resources using Terraform scripts, such as: Strapi Server (Cluster ECS Fargate), Database RDS Aurora PostgreSQL, Bucket S3 for Media Library, Load Balancer, Role IAM and Secrets SSM)
> [B2BP-174] - Terraform modify SecurityGroup ALB

- .infrastructure/03_network.tf
- .infrastructure/06_alb.tf
The deployinfra workflow fails with error _"RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached."_
This because the max number of (soft limit)Security Group rule is 60. The "aws_ec2_managed_prefix_list.cloudfront" counts as 55 rules. For this reason we need to create 2 different Security Group to use the "managed_prefix_list.cloudfront" for 80 and 1337 port. 
https://aws.amazon.com/it/blogs/networking-and-content-delivery/limit-access-to-your-origins-using-the-aws-managed-prefix-list-for-amazon-cloudfront/
_"if you add one managed prefix list for CloudFront in your Inbound rules. If you want to limit both HTTP and HTTPS requests using the managed prefix list for CloudFront, then you must add two separate rules, which will count as 110 total …
> [B2BP-174] - Terraform SPLIT SecurityGroup ALB

- apps/strapi-cms/src/api/footer/content-types/footer/schema.json
- apps/strapi-cms/src/api/footer/controllers/footer.ts
- apps/strapi-cms/src/api/footer/routes/footer.ts
- apps/strapi-cms/src/api/footer/services/footer.ts
- apps/strapi-cms/src/api/header/content-types/header/schema.json
- apps/strapi-cms/src/api/header/controllers/header.ts
- apps/strapi-cms/src/api/header/routes/header.ts
- apps/strapi-cms/src/api/header/services/header.ts
- apps/strapi-cms/src/api/pre-header/content-types/pre-header/schema.json
- apps/strapi-cms/src/api/pre-header/controllers/pre-header.ts
- apps/strapi-cms/src/api/pre-header/routes/pre-header.ts
- apps/strapi-cms/src/api/pre-header/services/pre-header.ts
- apps/strapi-cms/src/components/components/cta-button.json
- apps/strapi-cms/src/components/components/cta-group.json
- apps/strapi-cms/src/components/components/link-group.json
- apps/strapi-cms/src/components/components/link.json
- apps/strapi-cms/types/generated/components.d.ts
- apps/strapi-cms/types/generated/contentTypes.d.ts
This PR adds site-wide elements (Single Types) and the components needed for them to the Strapi CMS data structure.
The data's shape is based on the [Figma designs](https://www.figma.com/file/6Hn7Wxmvg6eCSqsMrIP7VU/CMS---UI-Components-%26-Templates?type=design&node-id=1-18544&mode=design&t=djDIr74ofFOmLCDR-0) and on the props requested by the [editorial components](https://pagopa.github.io/pagopa-editorial-components/?path=/docs/preheader-light--docs).
- Added PreHeader
- Added Header
- Added Footer
- Added CTAGroup component (used in PreHeader)
- Added CTAButton component (used in CTAGroup and Header)
- Added LinkGroup component (used in Footer)
- Added Link component (used in Footer and LinkGroup)
The data structure allows CMS users to define the respective elements to be rendered by …
> [B2BP-195] Added Single Types for PreHeader, Header and Footer.

- .infrastructure/04_secrets.tf
- .infrastructure/07_ecs.tf
- .infrastructure/08_ecr.tf
- .infrastructure/09_iam_role.tf
- .infrastructure/10_iam_access_key_strapi.tf
- .infrastructure/98_variables.tf
- .infrastructure/task-definitions/cms_app.json.tpl
Creation of Terraform scripts for the automatic deployment on AWS of ECS Task definition and ECR resources necessary for Strapi.
Creation of Terraform scripts for the automatic deployment on AWS of ECS Task definition and ECR resources necessary for Strapi.
As reported in the [RFC "SV-003 - Architettura Strapi on AWS"](https://pagopa.atlassian.net/wiki/spaces/SV/pages/795771078/SV-003+-+Architettura+Strapi+on+AWS), to host the Strapi instance on the AWS Cloud Provider it is necessary to create the relevant resources using Terraform scripts, such as: Strapi Server (Cluster ECS Fargate), Database RDS Aurora PostgreSQL, Bucket S3 for Media Library, Load Balancer, Role IAM and Secrets SSM)
Running Terraform scripts on locally PC pointing to a test AWS environment
> [B2BP-172] - Terraform ECS Task Definition AWS

- apps/nextjs-website/src/app/[...slug]/page.tsx
Quick fix of a type mismatch inside /nextjs-website7src/app/[...slug]/page.tsx
- Casted the return value of getAllPages from Promise<ReadonlyArray<Page>> to Promise<Page[]>
Fix the following error
`
.next/types/app/[...slug]/page.ts(37,98): error TS2344: Type '{ __tag__: "generateStaticParams"; __return_type__: Promise<readonly Page[]>; }' does not satisfy the constraint '{ __tag__: "generateStaticParams"; __return_type__: any[] | Promise<any[]>; }'.
Types of property '__return_type__' are incompatible.
Type 'Promise<readonly Page[]>' is not assignable to type 'any[] | Promise<any[]>'.
Type 'Promise<readonly Page[]>' is not assignable to type 'Promise<any[]>'.
The type 'readonly Page[]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.
`
Reran successfully using `npm run …
> [B2BP-167] Casted getAllPages value to remove readonly for generateStaticParams

- apps/strapi-cms/src/components/components/cta-button.json
- apps/strapi-cms/src/components/sections/editorial.json
- apps/strapi-cms/src/components/sections/feature.json
- apps/strapi-cms/src/components/sections/hero.json
- apps/strapi-cms/src/components/sections/how-to.json
- apps/strapi-cms/types/generated/components.d.ts
Front end (Next) implementation showed the necessity for two extra fields in the data structure:
1. An ID for sections to enable linking inside of a page (like #section-id)
2. A size property for CTA buttons
- Added size property to ctaButton component
- Added sectionID property to all sections
Replicate complete functionality of current SEND website.
Locally as per README.md
> [B2BP-229] Data structure adjustments

- apps/strapi-cms/config/plugins.ts
- apps/strapi-cms/types/generated/contentTypes.d.ts
Added plugins.ts file containing the default configuration for the Navigation Plugin so that we won't have to configure it every time the DB is changed or when deploying new instances.
Configurations inside plugins.ts, in order:
- Set Page as the component to link to navigation elements
- Set Page's 'name' property as the display name for the navigation elements
- Set Page's 'slug' property as the one to use to autofill the navigation elements' required URL field
- Set maximum levels to be rendered in the menu to 2
- Made it so that a parent having the 'menuAttached' flag does NOT mean the children should have it too
Avoiding having to configure the plugin every time the DB is changed or when deploying new instances.
Locally with a clean DB.
> [B2BP-218] Add Navigation Plugin configuration

- apps/nextjs-website/src/lib/fetch/types/LinkTypes.ts
- apps/nextjs-website/src/lib/footer.ts
'social' and 'wrapper' LinkTypes have been erroneously removed in merge of PR XX
This PR reinstates them so that we can work on removing them at a later date.
- Reinstated LinkTypes
- Added checks to filter LinkTypes
Out of scope for this Sprint
Locally as per README
> [B2BP-255] Reinstated social LinkTypes

- .infrastructure/09_iam_role_deploy.tf
Add privileges to iam role deploy-cms
Update policy for IAM Role Deploy CMS for ECS and ECR service
Workflow "Deploy_CMS" fails beacause the IAM Role Deploy CMS not have the necessary privileges on the ECS and ECR Services
on locally PC
> [B2BP-115] - Terraform Update IAM role deploy CMS

- .github/workflows/deploy_cms.yaml
Fix on Workflow GitHub "deploy_cms" for push trigger: when someone merge a pull request or push on main branch, the workflow "deploy_cms" terminate in error because the environment value=prod is not passed and the workflow does not take  the role needed to authenticate to AWS
Workflow file "deploy_cms.yaml"
when someone merge a pull request or push on main, the workflow "deploy_cms" terminate in error because the environment value=prod is not passed and the workflow does not take  the role needed to authenticate to AWS
> [B2BP-115] - Workflow Deploy CMS fix for automatic Deploy on Push

- .infrastructure/07_ecs.tf
- .infrastructure/task-definitions/cms_app.json.tpl
Add ECS var "AWS_BUCKET_ENDPOINT" and modify ECS var "CDN_URL" to fix the problem of loading images by strapi via cdn
Add ECS var "AWS_BUCKET_ENDPOINT" and modify ECS var "CDN_URL" 
To fix the problem of loading images by strapi via cdn
on personal AWS account
> [B2BP-325] - Add ECS var for strapi retrieve image from cdn

- .infrastructure/04_secrets.tf
- .infrastructure/07_ecs.tf
- .infrastructure/task-definitions/cms_app.json.tpl
Add new env var for ECS Task definition for deploy static site from Strapi to GitHub:
GITHUB_PAT
REPO_OWNER
REPO_NAME
WORKFLOW_ID
TARGET_BRANCH
@datalek: you need to create the PAT on GitHub and modify the "/cms/github_pat" secret in the AWS ParameterStore with the PAT value obtained
Add new env var for ECS Task definition for deploy static site from Strapi to GitHub:
GITHUB_PAT
REPO_OWNER
REPO_NAME
WORKFLOW_ID
TARGET_BRANCH
on AWS test account
> [B2BP-338] - Add ECS var for PAT token GitHub Strapi

- .changeset/hungry-kids-complain.md
- apps/nextjs-website/src/components/Footer.tsx
The `socialLinks` attribute passes through any prop other than icon.
This caused warnings such as "Invalid ARIA attribute `ariaLabel`. Did you mean `aria-label`?"
Formatted props of socialLinks to be acceptable HTML attributes:
- linkType --> linktype
- ariaLabel --> aria-label
Remove warnings + accessibility and SEO
> [B2BP-291] Format Footer's socialLinks attributes to remove warnings

- .changeset/nasty-socks-ring.md
- .changeset/wise-walls-give.md
- apps/nextjs-website/src/components/BannerLink.tsx
- apps/nextjs-website/src/lib/fetch/types/PageSection.ts
- apps/strapi-cms/src/components/sections/banner-link.json
Depends on #169 
Simplified BannerLink Section structure based on the requirements of the SEND website.
Strapi
- `reverse`: Had no effect. Removed.
- `ctaButtons`: Replaced `CTAButton` with `CTAButton_Simple`.
- `sectionID`: Added field.
NextJS
- Adapted types and parsing to reflect Strapi updates
- Utilized `sectionID`
Better CMS UX and more solid data parsing.
Tested locally + Unit tested.
> [B2BP-351] Simplify BannerLink Section

- .changeset/breezy-peaches-report.md
- apps/nextjs-website/src/lib/fetch/__tests__/footer.test.ts
- apps/nextjs-website/src/lib/fetch/__tests__/header.test.ts
- apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts
- apps/nextjs-website/src/lib/fetch/__tests__/preHeader.test.ts
- apps/nextjs-website/src/lib/fetch/footer.ts
- apps/nextjs-website/src/lib/fetch/header.ts
- apps/nextjs-website/src/lib/fetch/navigation.ts
- apps/nextjs-website/src/lib/fetch/preHeader.ts
An issue has emerged which lead us to believe NextJS is using stale cached data when building static websites.
Briefly put: Next seems to only generate totally new pages and update the homepage.
This creates inconsistencies in the deployed static website for any page that is not the homepage.
One possible culprit is [the code starting at the following line](https://github.com/pagopa/b2b-portals/blob/76351936af50bac2ee602ce5ea121cb0c1117179/.github/actions/deploy/action.yaml#L39), which seems to make it so NextJS always builds from cache, unless there's been some changes in the source code itself (which won't happen when a common CMS user updates data).
This PR prevents NextJS default caching behaviour in an attempt to solve the issue, forgoing cached data entirely from one build to the …
> [B2BP-397] Prevent caching of fetch response

- .changeset/famous-bottles-sin.md
- apps/nextjs-website/package.json
Enable coverage report.
> [!WARNING]  
> The `cloudfront-functions` app uses `rewire` to run tests. This dependency is necessary because the AWS runtime doesn't allow the keyword `export`, so we need to use `rewire`.
Unfortunately there is an [open issue with `rewire` that causes a `0%` coverage, even if there are tests](https://github.com/jhnns/rewire/issues/145).
Execute tests generating also the coverage report.
- Enable coverage in `nextjs-website`
We want to monitor the coverage.
> [B2BP-310] Enable coverage on tests

- .changeset/tidy-lies-warn.md
- apps/nextjs-website/package.json
- package-lock.json
- Updated the "@pagopa/pagopa-editorial-components" package from version 2.1.3 to 2.3.1
This change is necessary to incorporate the latest enhancements, bug fixes, and features provided by the new version of the "@pagopa/pagopa-editorial-components" package (from 2.1.3 to 2.3.1). By staying up-to-date with the latest package version, we ensure that our system benefits from improved performance, security patches, and additional functionality. Also this will import missing components from the previous version
> [B2BP-377] - Updating EC version from 2.1.3 to 2.3.1

- apps/nextjs-website/package.json
- package-lock.json
- Updated the "@pagopa/pagopa-editorial-components" package from version 2.3.2 to 2.3.3
This new version fix two bugs from EC about StripeLink and Bannerlink HTML rendering and improves some UI changes
> [B2BP-437] - Update EC version from 2.3.2 to 2.3.3

- .changeset/funny-lies-approve.md
- apps/nextjs-website/src/app/[[...slug]]/page.tsx
- apps/nextjs-website/src/app/layout.tsx
- apps/nextjs-website/src/app/manifest.ts
- apps/nextjs-website/src/lib/__tests__/pages.test.ts
- apps/nextjs-website/src/lib/api.ts
- apps/nextjs-website/src/lib/fetch/__tests__/data.ts
- apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts
- apps/nextjs-website/src/lib/fetch/__tests__/siteWideSEO.test.ts
- apps/nextjs-website/src/lib/fetch/navigation.ts
- apps/nextjs-website/src/lib/fetch/siteWideSEO.ts
- apps/nextjs-website/src/lib/fetch/types/SEO.ts
- apps/nextjs-website/src/lib/fetch/types/StrapiImage.ts
- apps/nextjs-website/src/lib/pages.ts
Implementing SEO NextJS-side based on [RFC SV-015](https://pagopa.atlassian.net/wiki/spaces/SV/pages/931627186/SV-015+Requisiti+di+SEO) and PR #183 
- Fetch `siteWideSEO`
- Populate `seo` field when fetching pages
- Add `generateMetaData` to `[[slug]]/page.tsx`
- Add `manifest.ts`
- Update `ImageDataCodec` to allow new fields needed for SEO (specifically manifest generation)
- Add + Update tests
Adding SEO to static websites.
> [B2BP-392] Implement SEO NextJS-side

- .changeset/early-jars-float.md
- apps/nextjs-website/package.json
- package-lock.json
- Updated the "@pagopa/pagopa-editorial-components" package from version 3.1.0 to 3.1.1
This new version will fix the "window" error on "Editorial" component from EC
> [B2BP-472] - Update EC version from 3.1.0 to 3.1.1

- .changeset/forty-elephants-deny.md
- apps/nextjs-website/next.config.js
- apps/nextjs-website/src/components/Editorial.tsx
- Converted img to next/image on Editorial.tsx file
- Added unoptimized: true to next.config.js
- Updated style
This PR will fix the warning about the "Using `<img>` could result in slower LCP and higher bandwidth". The result is to use "Image" from Next.JS in order to fix the warning. The unoptimized config was necessary due to "Image Optimization using the default loader is not compatible with `{ output: 'export' }`" so from the official Next.JS docs the solution of unoptimized images were implemented
Tested in local. To test, change this row
```src={image.url}```
into this row
```src={`http://localhost:1337${image.url}`}```
> [B2BP-481] Img to next/image warning fix

- .changeset/orange-plants-double.md
- apps/nextjs-website/package.json
- package-lock.json
- Updated the "@pagopa/pagopa-editorial-components" package from version 3.1.1 to 3.1.2
This new version will fix small Ui issues with BannerLink and HowTo components.
> [B2BP-495] - Update EC version from 3.1.1 to 3.1.2

- .changeset/bright-flies-act.md
- .changeset/fair-trains-invite.md
- .changeset/mean-seals-give.md
- apps/nextjs-website/package.json
- apps/nextjs-website/src/components/Editorial.tsx
- apps/nextjs-website/src/lib/fetch/__tests__/data.ts
- apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts
- apps/nextjs-website/src/lib/fetch/navigation.ts
- apps/nextjs-website/src/lib/fetch/types/PageSection.ts
- apps/strapi-cms/src/components/components/store-buttons.json
- apps/strapi-cms/src/components/sections/editorial.json
- apps/strapi-cms/src/components/sections/hero.json
- package-lock.json
- Updated the "@pagopa/pagopa-editorial-components" package from version 3.1.2 to 4.0.0
This new version will fix:
- Cards layout
- Hero size for FAQ page
- Added badges for "Editorial" components
> [B2BP-513] - Update EC version from 3.1.2 to 4.0.0

- .changeset/itchy-adults-begin.md
- apps/strapi-cms/package.json
- package-lock.json
After merging PR #262 the error still showed up in production, although it was fixed in a development / local environment.
Turns out this was due to Strapi not being able to build because it couldn't access the `@types/koa` dependency due to it being a devDependency.
This PR fixes that.
Moved `@types/koa` from devDependecies to dependencies.
Bug fix.
Tested in AWS environment analogous to our production environment.
> [B2BP-571] Move @types/koa depedency from devDependencies to standard dependencies

- .changeset/happy-beans-fry.md
- apps/nextjs-website/react-components/components/Header/Header.helpers.tsx
- apps/nextjs-website/react-components/components/Header/Header.tsx
- apps/nextjs-website/react-components/components/Header/components/HamburgerMenu.tsx
- apps/nextjs-website/react-components/components/Header/components/MenuDropdown.tsx
- apps/nextjs-website/react-components/components/Header/components/Navigation.tsx
- apps/nextjs-website/react-components/components/Header/components/Title.tsx
- apps/nextjs-website/react-components/components/index.ts
- apps/nextjs-website/react-components/types/Header/Header.types.ts
- apps/nextjs-website/react-components/types/index.ts
- apps/nextjs-website/src/components/Header.tsx
This PR refers to Option 3 from: [https://pagopa.atlassian.net/wiki/spaces/SV/pages/983531952/SV-021+Implementazione+componenti+EC+all+interno+di+B2BP#Opzione-3%3A-Integrazione-EC-su-B2BP-all%E2%80%99interno-della-cartella-Next.JS](url)
- Copied 'Header' component inside the folder apps\nextjs-website\react-components\components\Header
- Refactored 'Header' component for lint and more readability and code comprehension. Splitted in more small files.
- Created two files where all types and mid-blocks are exported instead of taking duplicated files inside each component
Move away from editorial-components entirely as a dependency to make updates easier and reduce times to fix bugs and integrating new functionalities.
The generated HTML equates the old one.
> [B2BP-559] - Implementing 'Header' EC inside B2BP

- .changeset/yellow-teachers-build.md
- apps/nextjs-website/package.json
- apps/nextjs-website/src/lib/header.ts
- package-lock.json
This PR refers to Option 3 from: [https://pagopa.atlassian.net/wiki/spaces/SV/pages/983531952/SV-021+Implementazione+componenti+EC+all+interno+di+B2BP#Opzione-3%3A-Integrazione-EC-su-B2BP-all%E2%80%99interno-della-cartella-Next.JS](url)
- Removed @PagoPa/Editorial-Components dependencies from B2BP
This is the last step to migrate all components used from EC library into B2BP
The generated HTML equates the old one.
> [B2BP-559] - Removing EC as dependencies

- .changeset/nasty-emus-argue.md
- apps/nextjs-website/src/app/layout.tsx
- apps/nextjs-website/src/lib/fetch/__tests__/siteWideSEO.test.ts
- apps/nextjs-website/src/lib/fetch/siteWideSEO.ts
- apps/strapi-cms/src/api/appio-general/content-types/appio-general/schema.json
- apps/strapi-cms/src/api/send-general/content-types/send-general/schema.json
As per title.
This PR adds the capability to optionally setup Matomo Analytics.
It currently only allows to set the site's ID used for tracking.
Any other additional configurations needed will be implemented with new PRs when requested.
- Add `matomoID` field to Strapi's General Single Type (for all tenants)
- Implement Matomo Analytics Script in NextJS
As described in task [B2BP-451](https://pagopa.atlassian.net/browse/B2BP-451?atlOrigin=eyJpIjoiN2NlMjQwYzZlMWI5NGIzZTgxZjllYTY0NDRiZjEyNzciLCJwIjoiaiJ9)
Locally tested the correct creation of the script.
Some production testing to make sure Matomo correctly gathers data is recommended.
[B2BP-451]: https://pagopa.atlassian.net/browse/B2BP-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [B2BP-451] Add Matomo Analytics

- .changeset/empty-lies-cheat.md
- apps/strapi-cms/src/api/page/content-types/page/schema.json
Strapi's "unique" constraint applies cross-tenant.
This made it so two tenants where unable to both have a page with slug "homepage", which is the special slug used to identify the site's home page and such every tenant should have one.
- Created pages with the same slug (works as expected)
- Inserted pages with the same slug in different navigations (works as expected)
- Inserted pages with the same slug in the same navigation (the auto-filled URL field blocks this action, as desired)
- Forcibly changed URL field to pass two pages with the same slug to NextJS. The site's build does not break, it instead simply renders the first of the pages with the same slug. This behaviour is acceptable given that any normal user not actively attempting to break the system will be stopped by the …
> [B2BP-625] Make Page's slug not unique

- .changeset/khaki-geese-talk.md
- apps/nextjs-website/react-components/components/Feature/FeatureStackItem.tsx
- apps/nextjs-website/react-components/components/Feature/Subtitle.tsx
- Fixed rendering method for subtitle when links are missing
Before Fix
After Fix
This PR is made to align components to the legacy version of SEND
Tested locally
> [B2BP-663] - Fix Feature rendering component

- .changeset/swift-elephants-kneel.md
- apps/nextjs-website/react-components/components/IFrame/IFrame.tsx
Remove hardcoded values in favor of `@iframe-resizer/react` library.
As described above.
Hardcoded values would only work with one specific page.
> [B2BP-589] Implement iframe-resizer/react into iFrame

- .changeset/purple-scissors-give.md
- apps/strapi-cms/config/plugins.ts
As per title.
- Added `tenant` query parameter (needed for new architecture)
- Enabled Preview Button plugin
Make Previews available again in new architecture.
Tested locally, also linking to online NextJS Preview Mode instance.
> [B2BP-698] Re-enabled Preview Button inside Strapi

- .changeset/quick-singers-draw.md
- apps/infrastructure/src/iam_policy.tf
- Removed s3:ListBucket permission in bucket policies
Currently, the list of objects contained in the medialibrary is publicly visible when reaching any of the medialibraries' cloudfront distributions
> [B2BP-780] - Avoid showing medialibrary objects list

- .changeset/seven-schools-perform.md
- apps/strapi-cms/src/index.ts
As per title.
- Overwritten default plugin behaviour
Limit each tenant's visibility so that they can only see their own workflow runs.
Tested locally fetching directly from Github.
Tenant 'demo'
Tenant 'send'
> [B2BP-784] Filter workflows shown in Strapi deploy plugin by tenant

- .changeset/smooth-clouds-help.md
- .changeset/tidy-pens-smile.md
- apps/nextjs-website/react-components/components/BannerLink/Content.tsx
- apps/nextjs-website/react-components/types/BannerLink/BannerLink.types.ts
- apps/nextjs-website/src/components/BannerLink.tsx
- apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts
- apps/nextjs-website/src/lib/fetch/navigation.ts
- apps/nextjs-website/src/lib/fetch/types/PageSection.ts
- apps/nextjs-website/stories/Bannerlink/bannerlinkCommons.tsx
- apps/strapi-cms/src/components/components/banner-link-section.json
- apps/strapi-cms/src/components/sections/banner-link.json
As per title.
NextJS-side
- Removed normalText, boldText, link and extraNormalText variables in favor of single `body` field to be rendered from markdown
- Updated population parameters when fetching pages to be able to render every field of BannerLink's multiple sections (more specifically decoration and ctaButtons)
Strapi-side
- Updated BannerLink component to reflect new props structure
BannerLink now requires the capability for multiple sections.
Tested locally running from local Strapi instance.
Tested storybook working correctly after update.
> [B2BP-802] Update BannerLink to add multiple sections

- .changeset/twenty-shrimps-prove.md
- apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts
- apps/nextjs-website/src/lib/fetch/preview.ts
As per title.
Previous PR fixed standard static deploy after the introduction of multiple sections to the `BannerLink` component.
This PR fixes the preview.
- Added needed population parameters when fetching from Strapi
Bug fix. Render component correctly in preview.
Tested locally, fetching data from production Strapi instance.
> [B2BP-802] Add population parameters for new BannerLink to preview

- .changeset/modern-starfishes-retire.md
- apps/strapi-cms/src/components/components/form-category.json
Strapi's unique constraint handling seems to check against itself, forcing to always update all unique constraints to be able to save any changes.
This PR removes the unique constraints in the Form Category component to solve the problem.
- Remove unique constraints from Form Category fields
Bug fix / Better UX
> [B2BP-853] Remove unique constraint from Form Category fields

- .changeset/rare-eyes-allow.md
- apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx
- apps/nextjs-website/react-components/types/Hero/Hero.types.ts
- apps/nextjs-website/src/components/Hero.tsx
- apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts
- apps/nextjs-website/src/lib/fetch/types/PageSection.ts
- apps/nextjs-website/stories/Hero/dark.stories.tsx
- apps/nextjs-website/stories/Hero/light.stories.tsx
- Added the optional link below the storeButtons in Hero component
This PR is made to add the tertiary link below the storeButtons in Hero component
Tested locally
> [B2BP-850] - Implement tertiary Link for Hero component

- .changeset/serious-bottles-serve.md
- apps/nextjs-website/src/components/Feature.tsx
- apps/nextjs-website/src/components/HowTo.tsx
- apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts
- apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts
- apps/nextjs-website/src/lib/fetch/navigation.ts
- apps/nextjs-website/src/lib/fetch/preview.ts
- apps/nextjs-website/src/lib/fetch/types/PageSection.ts
- apps/strapi-cms/src/components/components/feature-item.json
- apps/strapi-cms/src/components/components/step.json
As per title.
Subbed `themedIcon` for `icon` in Feature and HowTo components both in Strapi and NextJS.
Better UX.
Ran locally in dev and preview.
> [B2BP-921] Substitute Themed Icon with a simple Icon

- .changeset/wet-pumpkins-exercise.md
- apps/nextjs-website/src/components/Feature.tsx
- apps/nextjs-website/src/components/HowTo.tsx
As per title.
A dev-only workaround to make image urls work (prepending 'http://127.0.0.1:1337') 
- Remove 'http://127.0.0.1:1337' before image URLs
A dev-only workaround to make image URLs work (prepending 'http://127.0.0.1:1337') got through reviews.
This breaks prod as the image's url are then invalid.
This PR fixes that.
Ran locally.
> [B2BP-931] Remove dev URL for icons

- .changeset/slimy-berries-wonder.md
- apps/strapi-cms/src/components/shared/seo.json
As per title
Updated maxLength of ogDescription field from 65 to 160
Consistency with metaDescription
> [B2BP-961] Extend og:description to 160 characters

- .changeset/popular-paws-stare.md
- apps/strapi-cms/src/components/sections/accordion.json
As per title.
Give the ability to CMS user to choose whether the Accordion title sits on top or beside the questions in desktop view.
- Repurpose layout field to indicate where the title will be (left of questions or centered above them)
- Add textAlignment field to indicate text alignment when layout is 'center'
Feature request
Ran locally
> [B2BP-913] Strapi Accordion add two-column layout

- .changeset/eighty-gifts-camp.md
- apps/nextjs-website/src/app/[[...slug]]/page.tsx
- apps/nextjs-website/src/app/robots.ts
- apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts
- apps/nextjs-website/src/lib/fetch/types/SEO.ts
- apps/strapi-cms/src/components/shared/seo.json
As per title
Strapi
- Add structuredData field as JSON to Page's `seo` section
NextJS
- Conditionally render structuredData following [NextJS docs](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld)
Feature request
Needs prod testing using Google's [Rich Results Test](https://search.google.com/test/rich-results).
> [B2BP-964] Add structuredData to page SEO

- apps/nextjs-website/react-components/components/PreFooter/PreFooter.tsx
- apps/nextjs-website/react-components/types/PreFooter/PreFooter.ts
- apps/nextjs-website/src/app/layout.tsx
- apps/nextjs-website/src/components/PreFooter.tsx
- apps/nextjs-website/src/lib/api.ts
- apps/nextjs-website/src/lib/fetch/__tests__/preFooter.test.ts
- apps/nextjs-website/src/lib/fetch/preFooter.ts
- apps/nextjs-website/src/lib/fetch/types/PageSection.ts
- apps/strapi-cms/src/api/pre-footer/content-types/pre-footer/schema.json
- apps/strapi-cms/src/api/pre-footer/controllers/pre-footer.ts
- apps/strapi-cms/src/api/pre-footer/routes/pre-footer.ts
- apps/strapi-cms/src/api/pre-footer/services/pre-footer.ts
As per title.
- Add `PreFooter` Single Type to Strapi
- In NextJS, convert PreFooter component to site-wide component
- Add field `exclude` to conditionally render PreFooter only on not-excluded pages
New component
Ran locally in dev (being a site-wide component, PreFooter won't show in preview)
> [B2BP-917] Add PreFooter as site-wide component

- .changeset/clever-flowers-hunt.md
- apps/strapi-cms/src/components/sections/row-text.json
Depends on #490 
As per title.
- Changed RowText's "body" field to be a Rich Text (markdown)
Ran locally in dev and preview
> [B2BP-1004] Strapi RowText: Turned body field into Rich Text

- .changeset/green-dots-juggle.md
- apps/strapi-cms/Dockerfile
- apps/strapi-cms/config/plugins.ts
- apps/strapi-cms/package.json
- package-lock.json
As per title.
Adding the plugin previously caused the "Deploy CMS" action to fail running `npm i`.
The problem has not been possible to replicate locally by simply running `npm i`.
However, running `docker build` does replicate the issue.
Adding the `--force` or `--legacy-peer-deps` options to `Dockerfile` did not solve the issue, however switching from npm to yarn did. That is the solution presented in this PR.
- Install and configure Strapi Plugin Copy Locales
- Switch from using npm to yarn in Strapi's `Dockerfile`
Feature Request + Bug Fix
Ran locally in dev.
Built locally using docker.
> [B2BP-1019] Add Strapi Plugin Copy Locales

- .changeset/famous-clouds-study.md
- apps/nextjs-website/src/app/preview/page.tsx
- apps/nextjs-website/src/lib/api.ts
- apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts
- apps/nextjs-website/src/lib/fetch/preview.ts
As per title.
- Converted function `getPageSectionsFromID` to `getPageDataFromID` which now returns the page's locale as well
- Used the updated function to fetch the correct set of PressReleases in Preview mode
Make preview more closely represent the build output
Ran locally with pages of both locales (it/en)
> [B2BP-1067] Make PressReleaseList fetch correct PressReleases in Preview

- .changeset/cuddly-cars-fold.md
- .changeset/real-swans-sparkle.md
- apps/nextjs-website/src/app/preview/page.tsx
- apps/nextjs-website/src/lib/api.ts
- apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts
- apps/nextjs-website/src/lib/fetch/preview.ts
- apps/nextjs-website/src/lib/pressRelease.ts
- apps/strapi-cms/config/plugins.ts
As per title.
- Update Strapi's Preview Button plugin configuration to be active for PressRelease Collection Type and to add a "type" query parameter to distinguish between standard pages and press releases (so NextJS knows which one to fetch since it cannot determine from the ID alone)
- Make NextJS fetch from PressRelease or Page Collection Type depending on the value of the "type" query parameter
Better CMS UX
Ran locally in preview for all current locales (it/en)
> [B2BP-1065] Extend preview feature to PressRelease Collection Type

- .changeset/ten-spiders-exercise.md
- apps/strapi-cms/package.json
- apps/strapi-cms/src/api/page/content-types/page/schema.json
- apps/strapi-cms/src/api/press-release/content-types/press-release/schema.json
- package-lock.json
Made the slugs of Page and PressRelease unique.
This, however, breaks the clone/duplicate button function, so the Duplicate Button plugin has been added to maintain the functionality.
The plugin differs from Strapi's standard clone function in that the button is located in each Page's details page instead of the list view.
This plugin should be rendered moot when we'll upgrade to Strapi v5.
- Make Page and PressRelee slug unique
- Add Duplicate Button Strapi plugin
(Near) Guarantee slug uniqueness, while maintaining cloning functionality.
Ran locally.
> [B2BP-899] Make slugs unique and add Duplicate Button plugin

- .changeset/modern-bees-remember.md
- apps/nextjs-website/src/components/Header.tsx
As per title.
- Add sectionID (if present) as hash to links of MegaHeader
Bug Fix / Missing Implementation NextJS-side
> [B2BP-1083] Include sectionID in MegaHeader links

- apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
- apps/cloudfront-functions/src/viewer-request-handler.ts
Removed trailing slashes (/) from URIs.
This change is required to ensure consistent handling of URIs for a static website hosted behind CloudFront.
> [B2BP-1011] Normalize URI in cloudfront-functions

- .changeset/silent-parrots-learn.md
- apps/nextjs-website/react-components/components/Form/Form.tsx
Make it so Form optional fields (name, surname, organization) are either all passed or none is passed.
This is a limitation of the current middle man server / API we send requests to: the name, surname and organization fields have to either all be there or none at all.
The homepage forum (which subscribes people to the newsletter) currently only asks for name and surname, as such the API was sending no data to the mailup newsletter service, generating the 400 error.
- Update conditional and add default values for non-user-entered optional values
Bug fix
> [B2BP-1104] BUG FIX: Newsletter subscription fails with a 400 error

- .changeset/brown-teachers-cry.md
- apps/nextjs-website/src/app/[[...slug]]/layout.tsx
- apps/nextjs-website/src/components/ConsentHandler.tsx
Refactor came about while testing to see why OneTrust's otSDKStub script would not set cookies.
The reason was the data-domain-script (aka domain id) which did not include "-test" at the end of it.
I'm pushing the refactor anyway for better clarity and optimization of code.
Better maintanability
> [B2BP-1146] Refactor ConsentHandler

- .changeset/bright-taxis-turn.md
- apps/nextjs-website/src/components/ConsentHandler.tsx
Setting track_pageview to 'url-with-path' makes it so mixpanel now tracks pageview when the URL changes, ignoring parameter and hash changes.
Before, the value of the field was 'true', which meant pageviews were only tracked on page load (which apparently does not include changing pages).
- Updated value in mixpanel initialization
Bug fix
Ran locally, needs prod testing by verifying correct data tracking on mixpanel
> [B2BP-1158] Mixpanel: Automatic pageview tracking set to url-with-path

- apps/nextjs-website/src/app/[[...slug]]/page.tsx
- apps/nextjs-website/src/components/ConsentHandler.tsx
- apps/nextjs-website/src/components/TrackPageView.tsx
Automatic pageview tracking solutions offered by Mixpanel don't seem to work, possibly due to our sites being statically generated.
Change implementation to just initialize mixpanel with tracking disabled and track page views manually after consent is given.
- Remove automatic pageview tracking
- Modify initialization and separate it from tracking opt-in
- Call mixpanel.track_pageview inside each page
Bug fix
Ran locally in dev. Verified that opt in status gets saved correctly.
> [B2BP-1158] Mixpanel: Track page views manually

- .changeset/eleven-kiwis-wave.md
- apps/nextjs-website/src/components/Header.tsx
As per title.
Prevent Windows Phone users from being sent to Google Play
> [B2BP-1177] Handle Windows Phone user agent when opening app store from Header

- .changeset/chatty-eagles-brake.md
- apps/nextjs-website/src/components/ConsentHandler.tsx
As per title
Avoid flooding mixpanel with unnecessary opt_in events, while still making sure all users are explicitely opted_in, since the past implementation could have left them opted_out.
It's a small edge case, but we should address it, especially since the effort to do so is low.
> Bug Fix - MixPanel: Opt in after init only if user was opted out

- .changeset/sixty-sloths-hide.md
- apps/nextjs-website/react-components/components/common/StoreButtons.tsx
Refactored storeButtons to use MUI Link with target='_blank' instead of MUI Button to fix issue in the title.
Bug Fix
Struggled to test locally in dev, needs more test in prod / QA
> [B2BP-1209] Bug Fix: StoreButtons event not registering immediately

- .changeset/thick-pandas-behave.md
- apps/nextjs-website/package.json
- apps/nextjs-website/react-components/components/Accordion/AccordionItem.tsx
- apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
- apps/nextjs-website/react-components/components/common/StoreButtons.tsx
- apps/nextjs-website/src/components/ConsentHandler.tsx
- apps/nextjs-website/src/components/TrackPageView.tsx
- package-lock.json
As per title.
- Disabled mixpanel's default batching behaviour which prevented link tracking event to immediately be sent to the mixpanel dashboard
- Refactored storeButtons to use track_links function instead of standard track
- Removed checks on mixpanel.has_opted_in_tracking and substituted them with checks on !mixpanel.has_opted_out_tracking, this because both values can be false and this way we can check the user has not explicitely opted out of tracking, while not removing tracking is has_opted_in_tracking wrongfully returns false as it did until now
Bug Fix
Ran locally in dev and on iOS (Safari and Chrome)
> [B2BP-1210] Update mixpanel configuration and implementation to work on iOS and track links

- .changeset/perfect-impalas-peel.md
- apps/nextjs-website/react-components/components/IFrame/IFrame.tsx
- apps/nextjs-website/react-components/types/IFrame/IFrame.types.ts
This bug was brought to light by the use of the [OperatorsTable](https://github.com/pagopa/pn-showcase-site/blob/develop/src/components/Ritiro/OperatorsTable.tsx) component inside a child page of an iFrame component.
A showcase website user changing the pagination size of an OperatorsTable would NOT cause the iFrame to resize accordingly.
This because iframe-resizer (the library currently used to resize the parent iframe according to the child's content) does not seem to detect changes in height given by the content (in this case the OperatorsTable) changing in size, hence the standard `parentIframe.resize` does not work.
As a solution, the following workaround has been implemented: on pagination size change or on page change (which is problematic if the new page has more or less elements …
> [B2BP-1221] Implement workaround for iframe-resizer's resize function not working

- .changeset/rotten-badgers-flow.md
- apps/strapi-cms/package.json
- package-lock.json
As per title.
This update makes it so user will have to have specific permissions to see the deploy history and to trigger new builds.
CMS UX
> [B2BP-1224] Update strapi-plugin-static-deploy to add RBAC

- .changeset/nine-sloths-mate.md
- apps/strapi-cms/config/admin.ts
- apps/strapi-cms/config/server.ts
Implemented password recovery for CMS users.
- Configure Amazon SES
- Update config/admin's forgotPassword.emailTemplate field
- Add env variable containing CMS's admin panel's URL to be used in the password recovery email
CMS user autonomy
Tested locally using MailDev
> [B2BP-879] Officialize admin password-recovery email

- .changeset/wise-dodos-listen.md
- apps/nextjs-website/react-components/components/IFrame/IFrame.tsx
As per title.
Implemented using messages (parent.postMessage on child page and event handler for 'message' on parent).
Expected message is structured like so: `{ type: 'scrollTo', target: 'section-id' }`
- Add 'message' event handler to iFrame component
Feature Request (SEND)
> [B2BP-1298] iFrame: Allow child page to request scrolling to a section outside of the iframe
