.github/labels.yaml, .github/workflows/pr_enrich.yaml
Improve `pr_enrich` workflow, adding labels.
=> [B2BP-21, B2BP-22] Add labels

.github/auto_assign.yaml, .github/workflows/pr_enrich.yaml
Create job that assigns PR.
The assignee will be the author of the PR.
=> [B2BP-23] Add assignee job

.github/actions/setup-node/action.yaml, .github/workflows/code_review.yaml
Add workflow that:
- Check package-lock.json is up to date
- Install dependencies
- Compile project
- Lint code
- Run tests
=> [B2BP-16, B2BP-17, B2BP-18, B2BP-19, B2BP-27] Create code review workflow

.github/actions/setup-node/action.yaml, .github/workflows/code_review.yaml
Add step to upload code coverage report to CodeCov.
=> [B2BP-20] Add code coverage report

.github/actions/branch-up-to-date/action.yaml, .github/actions/link-pr-to-jira-activity/action.yaml, .github/workflows/check_branch_update.yaml
- Create a workflow that checks the PR branch is up to date with target branch
We want to make sure the author of the PR is notified when the merge/rebase operation needs to be done before merge.
=> [B2BP-25] - Verify PR branch is updated

.github/workflows/code_review.yaml
- Verify trigger is pull_request when executing step in workflow
We do not need a report about new dependencies when trigger is `push`
=> [B2BP-43] Check new dependencies installed only on pull_request trigger

.github/workflows/pr_enrich.yaml
Before this commit the workflow did not ignore the package-lock.json file to size the PR. After this commit it does.
=> [B2BP-45] Add ignored files to pr_enrich workflow

apps/nextjs-website/.eslintrc.json, apps/nextjs-website/package.json, apps/nextjs-website/src/app/layout.tsx, apps/nextjs-website/src/app/page.tsx, package-lock.json
- Add all eslint related dependencies
- Add eslint config
- Lint the code
Improves readability and consistency with the rest of projects.
Tested locally
=> [B2BP-98] Add eslint config for nextjs-website

.github/labels.yaml
Add the following labels:
- `docs`
- `changeset`
- `website`
=> [B2BP-100] Add new labels

.github/workflows/changelog.yaml, .github/workflows/check_branch_update.yaml, .github/workflows/check_pr_title.yaml, .github/workflows/code_review.yaml, .github/workflows/code_review_infra.yaml, .github/workflows/deploy_infra.yml, .github/workflows/github_release.yaml
Upgrade of action "checkout" version to v4.0.0 in github workflows
Upgrade action "checkout" version to v4.0.0 in github workflows
Alignment and update action "checkout" version
Execute workflows and verify the "checkout code" operation
=> [B2BP-118] - Upgrade the version of actions/checkout

.github/actions/setup-terraform/action.yaml, .github/labels.yaml, .infrastructure/env/prod/terraform.tfvars, .infrastructure/identity/main.tf
We want to automatically verify the formatting of Terraform files.
- Pass the infrastructure folder to action that run the `fmt` command
- Add `-recursive` option to let terraform check formatting also in subfolders
- Lint terraform files
We want a feedback about wrong indentation of Terraform files
=> [B2BP-141] Add -recursive option

.infrastructure/01_iam_user.tf, .infrastructure/02_iam_group.tf
- Create IAM User
- Create User Group
- Create Policy Attachment
We want to give a ReadOnly access to AWS resources to the external contractors.
=> [B2BP-142] - Add IAM Users

.infrastructure/03_s3.tf
Creation of Terraform scripts for the automatic deployment on AWS of S3 bucket necessary for Strapi
Creation of Terraform scripts for the automatic deployment on AWS of bucket S3 necessary for Media Library Strapi
As reported in the [RFC "SV-003 - Architettura Strapi on AWS"](https://pagopa.atlassian.net/wiki/spaces/SV/pages/795771078/SV-003+-+Architettura+Strapi+on+AWS), to host the Strapi instance on the AWS Cloud Provider it is necessary to create the relevant resources using Terraform scripts, such as: Strapi Server (Cluster ECS Fargate), Database RDS Aurora PostgreSQL, Bucket S3 for Media Library, Load Balancer, Role IAM and Secrets.
Running Terraform scripts on locally PC pointing to a test AWS environment
=> [B2BP-168] - Terraform S3 Media Library AWS

.github/actions/branch-up-to-date/action.yaml, .github/actions/link-pr-to-jira-activity/action.yaml
> The best practice to avoid code injection vulnerabilities in GitHub workflows is to set the untrusted input value of the expression to an intermediate environment variable and then use the environment variable using the native syntax of the shell/script interpreter (that is, not ${{ env.VAR }}).
According to GitHub, within `run` or `scripts` in GitHub action, [it is more safe to use the shell syntax to get environment variable](https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure/#1-dont-use-syntax-in-the-run-section-to-avoid-unexpected-substitution-behavior).
This fixes https://github.com/pagopa/b2b-portals/security/code-scanning/1, https://github.com/pagopa/b2b-portals/security/code-scanning/2 and …
=> [B2BP-177] - Use shell syntax to read environment variables

apps/nextjs-website/.eslintrc.json, apps/nextjs-website/package.json, apps/nextjs-website/src/app/page.tsx, package-lock.json
- Install `pagopa-editorial-components`
- Downgrade eslint dependencies to be compatibile with version of `eslint-config`
- Use eslint recommended config
- Add editorial components Hero to the homepage to show that works
The system should use editorial-components
Locally
=> [B2BP-182] Install pagopa-editorial-components dependency

.infrastructure/03_network.tf, .infrastructure/98_variables.tf
Creation of Terraform scripts for the automatic deployment on AWS of Networking resources necessary for Strapi.
Creation of Terraform scripts for the automatic deployment on AWS of Networking resources necessary for Strapi.
As reported in the [RFC "SV-003 - Architettura Strapi on AWS"](https://pagopa.atlassian.net/wiki/spaces/SV/pages/795771078/SV-003+-+Architettura+Strapi+on+AWS), to host the Strapi instance on the AWS Cloud Provider it is necessary to create the relevant resources using Terraform scripts, such as: Strapi Server (Cluster ECS Fargate), Database RDS Aurora PostgreSQL, Bucket S3 for Media Library, Load Balancer, Role IAM and Secrets SSM)
Running Terraform scripts on locally PC pointing to a test AWS environment
=> [B2BP-174] - Terraform Network AWS

apps/nextjs-website/package.json, package-lock.json, package.json
- Add `overrides` as a workaround to fix the version of react and react-dom
- Regenerate `package-lock.json`
Both applications (nextjs-website and strapi-cms) started raising errors at runtime. The problem is caused by forced resolution to react@17.2.0 caused by the [react-swipeable-views](https://github.com/pagopa/pagopa-editorial-components/blob/bdd66ac/package.json#L74-L75) library which doesn't include [react@18.0.0](https://github.com/oliviertassinari/react-swipeable-views/blob/be57b7d/packages/react-swipeable-views-utils/package.json#L28-L30).
Locally. Run the following commands:
```
find . -name 'node_modules' -type d -prune -print -exec rm -rf '{}' \;
npm i
npm run dev
```
Both application run without any errors.
=> [B2BP-190] Add overrides react version

.infrastructure/06_alb.tf, apps/strapi-cms/config/database.ts, apps/strapi-cms/package.json, package-lock.json
This PR adds the capability for PostgreSQL connection to the Strapi CMS.
It has previously only been able to connect to SQLite for testing purposes.
- Updated config/database.ts to include postgres configuration
- Added pg module (postgres client)
- First step towards CMS deployment
A local PostgreSQL DB has been created.
A full functionality test, following the procedures detailed in the root README file, has followed.
=> [B2BP-192] Configured Strapi to accept PostgreSQL connections

apps/nextjs-website/src/app/[...slug]/page.tsx
=> Revert "[B2BP-167] Casted getAllPages value to remove readonly for generateStaticParams"

.github/CODEOWNERS
Add `b2bportals-maintain` as CODEOWNER.
Depends on https://github.com/pagopa/eng-github-authorization/pull/563
- Create CODEOWNERS file
=> [B2BP-184] Create CODEOWNERS

apps/strapi-cms/src/admin/tsconfig.json, apps/strapi-cms/tsconfig.json
Removed extends inside Strapi's tsconfig files and manually copied extended configurations.
Could not deploy folder /apps/strapi-cms/ on its own otherwise.
On a private ECS instance.
=> [B2BP-115] Removed extends inside Strapi's tsconfig files

apps/nextjs-website/src/lib/api.ts, apps/nextjs-website/src/lib/fetch/__tests__/footer.test.ts, apps/nextjs-website/src/lib/fetch/footer.ts, apps/nextjs-website/src/lib/fetch/types/LinkTypes.ts, apps/nextjs-website/src/lib/footer.ts
- Move some transformation from `src/lib/api.ts` to `src/lib/footer.ts`
- Change Footer Codec
Unit Test and locally
=> Review to footer component

apps/nextjs-website/src/lib/footer.ts
Suggestion related to #89 
Locally and unit tests
=> PR-89 review

apps/nextjs-website/src/lib/footer.ts
Added the following line to the file `apps\nextjs-website\src\lib\footer.ts`:
showFundedByNextGenerationEULogo: attributes.showFundedByNextGenerationEULogo,
This change is introduced to facilitate the display of the "Funded by Next Generation EU" logo within the footer of the Next.js website. Including this line in the `footer.ts` file ensures that the logic for handling the visibility of the logo is properly integrated into the codebase.
Testing for this change has been conducted in a controlled environment. I verified its impact on the website's footer functionality, ensuring that the "Funded by Next Generation EU" logo appears or disappears based on the specified attributes. The testing environment included running relevant unit tests and assessing any potential interactions with other …
=> [B2BP-278] - Missing showFundedByNextGenerationEULogo inside the footer.ts file

.gitattributes
* Add `.gitattributes` file with the line "* text=auto".
Ensure consistent handling of line endings across different platforms[^1]. Helps prevent issues related to line ending differences between operating systems.
[^1]:https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=mac
=> [B2BP-298] Add .gitattributes file

apps/nextjs-website/src/app/[...slug]/page.tsx
Implemented rendering sections for any page, same as for the homepage.
Next step in replicating the whole SEND website.
=> [B2BP-300] Added section rendering to slug/page

.github/workflows/deploy_cms.yaml
Add permission in job github for OIDC authentication:
permissions:
id-token: write
contents: read
Add permission in job github for OIDC authentication:
permissions:
id-token: write
contents: read
Fix the error "Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers" when job start on pull request
=> [B2BP-115] - Add permission job github deploy cms

.infrastructure/07_ecs.tf, .infrastructure/task-definitions/cms_app.json.tpl
add cdn_url environment variable for retrieve a media by Static Site and Strapi from cdn_medialibrary.
Without CDN_URL variable, the static site not retrieve a media from media library.
add cdn_url environment variable in terraform file
add cdn_url environment variable for retrieve a media by Strapi from medialibrary
=> [B2BP-115] - terraform add cdn url var

.github/workflows/deploy_infra.yml
Cloudfront function for add html extension in static site request
Modify workflow file
Cloudfront function for add html extension in static site request
=> [B2BP-305] - Add cloudfront function in workflow deploy cms

.github/workflows/deploy_infra.yml
Reverts pagopa/b2b-portals#121
=> Revert "[B2BP-305] - Add cloudfront function in workflow deploy cms"

.github/workflows/deploy_infra.yml
Add compile to deploy_infra workflow
The function needs to be compiled to be used by the infrastructure.
No
=> [B2BP-305] Update deploy_infra workflow

.github/workflows/code_review_infra.yaml
Compile cloudfront-functions also during code_review_infra workflow
Cloudfront functions app is compiled only on deploy_infra workflow.
=> Compile cloudfront functions also in code_review_infra workflow

.changeset/eight-pugs-rest.md, apps/cloudfront-functions/package.json, apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts, apps/cloudfront-functions/src/viewer-request-handler.ts, package-lock.json
Remove invalid `export` keyword from Cloudfron function
- Remove invalid keyword
- Improve unit tests
We had a runtime error when executing the function
Unit tests
=> Fix Cloudfront function

.github/workflows/code_review.yaml
- Add missing env into workflow
The token was missing
=> Add missing codecov token

.github/workflows/changelog.yaml, package.json
Fix changelog workflow (that uses changesets) refactoring a command.
=> Move npm i outside the action

apps/strapi-cms/src/api/page/content-types/page/schema.json, apps/strapi-cms/src/components/components/accordion-item.json, apps/strapi-cms/src/components/sections/accordion.json
Added Accordion section to Strapi
- Created AccordionItem
- Created Accordion (using AccordionItem)
- Added Accordion to Page's "sections" field
Needed for duplicating SEND's website.
=> [B2BP-332] Added Accordion section to Strapi

.infrastructure/09_iam_role.tf
Added privilege GetParameter for github_pat secret on ECS policy.
Added privilege GetParameter for github_pat secret on ECS policy.
Added privilege GetParameter for github_pat secret on ECS policy.
=> [B2BP-338] - Add ECS GetParameter for PAT secret

.infrastructure/09_iam_role.tf, .infrastructure/11_dns.tf, .infrastructure/98_variables.tf, .infrastructure/99_outputs.tf, .infrastructure/env/prod/terraform.tfvars
Add DNS zone for CMS Strapi by Terraform scripts with module "dns_zone"
Modify Terraform file for add DNS zone for CMS Strapi
=> [B2BP-340] - Terraform add DNS zone for Strapi

.changeset/six-lamps-chew.md, apps/nextjs-website/src/components/PreHeader.tsx, apps/nextjs-website/src/lib/fetch/__tests__/preHeader.test.ts, apps/nextjs-website/src/lib/fetch/preHeader.ts, apps/nextjs-website/src/lib/fetch/types/mui/ButtonIcon.ts, apps/nextjs-website/src/lib/fetch/types/mui/ButtonSize.ts, apps/strapi-cms/src/api/pre-header/content-types/pre-header/schema.json, apps/strapi-cms/src/components/components/pre-header-button.json
Simplified PreHeader structure based on the requirements of the SEND website.
- Updated Strapi Structure
- Updated API call URL
- Updated parsing functions
Better CMS UX and more solid data parsing.
Tested locally + Unit tested.
=> [B2BP-289] Simplify PreHeader

.changeset/slow-mangos-pump.md, apps/nextjs-website/src/components/HowTo.tsx
- Styled HowTo
Needed to replicates [SEND's website](https://notifichedigitali.pagopa.it/).
=> [B2BP-252] Styling HowTo Component

.changeset/spotty-geckos-judge.md, .changeset/sweet-elephants-joke.md, .changeset/weak-poets-matter.md, apps/nextjs-website/src/components/Feature.tsx, apps/nextjs-website/src/components/Icons/index.ts, apps/strapi-cms/src/components/components/footer-link-social.json
Above mentioned issues:
- Footer on Strapi's side had extra MuiSocialIcons not accepted by NextJS
- Feature component would not show icons correctly
- Removed extra MuiSocialIcons from Strapi
- Converted Feature component to use a standard string instead of the `Icon` component
Bug fixes.
=> [B2BP-288] Fixed minor issues with Footer and Feature components

.infrastructure/11_dns.tf
Modify dns terraform file for fix the dns A record
Modify dns terraform file for fix the dns A record
dns A record require Alias for ALB service
on DGS AWS account
=> [B2BP-341] - Terraform Fix DNS record

.changeset/wise-walls-give.md, apps/nextjs-website/src/components/BannerLink.tsx
As per title.
- Set `src`, `width` and `height` fields for `decoration` so that the (optional) image gets rendered correctly
Replicate [SEND website](https://notifichedigitali.pagopa.it/faq).
=> [B2BP-253] Style BannerLink Section

.changeset/nice-snails-complain.md, apps/nextjs-website/src/components/Accordion.tsx
As per title.
- Set `description` text color when in dark mode
Replicate [SEND website](https://notifichedigitali.pagopa.it/faq).
=> [B2BP-390] Style Accordion Section

.infrastructure/11_dns.tf
Add new dns record by Terraform for www.b2bportals.pagopa.it
Add new dns record by Terraform for www.b2bportals.pagopa.it
Add new dns record by Terraform for www.b2bportals.pagopa.it
=> [B2BP-320] - Terraform add dns record for www url cms

.changeset/slimy-dragons-prove.md, apps/nextjs-website/src/components/Feature.tsx, apps/nextjs-website/src/lib/fetch/types/PageSection.ts, apps/nextjs-website/src/lib/fetch/types/mui/FeatureItemIcon.ts, apps/strapi-cms/src/components/components/feature-item.json, apps/strapi-cms/src/components/sections/feature.json
Simplified Feature Section structure based on the requirements of the SEND website.
Strapi
- `background`: Unused field. Removed. It was used to set the background's color, which is dependent on the theme anyway.
- `sectionID`: Removed unique clause. Strapi was not handling it correctly and seemed to be checking it against itself, resulting in an error when NOT updating sectionID, which made it unusable.
- `items`: Removed iconColor (will be derived from theme). Restricted icon to a set of 8 MUI icons close to the ones currently used on the SEND website. Made icon required.
NextJS
- Adapted types and parsing to reflect Strapi updates
Better CMS UX and more solid data parsing.
Tested locally + Unit tested.
=> [B2BP-348] Simplify Feature Section

.infrastructure/13_dashboard.tf, .infrastructure/14_alarm.tf
By Terraform, Add Cloudwatch Alarm on RDS, ECS, CDN and ALB.
Add Terraform Alarm file
By Terraform, Add Cloudwatch Alarm on RDS, ECS, CDN and ALB.
=> [B2BP-358] - Terraform Add Cloudwatch Alarm

.changeset/popular-dingos-ring.md, apps/strapi-cms/package.json, apps/strapi-cms/src/api/general/content-types/general/schema.json, apps/strapi-cms/src/api/general/controllers/general.ts, apps/strapi-cms/src/api/general/routes/general.ts, apps/strapi-cms/src/api/general/services/general.ts, apps/strapi-cms/src/api/page/content-types/page/schema.json, apps/strapi-cms/src/components/shared/manifest.json, apps/strapi-cms/src/components/shared/seo.json, package-lock.json
Implementing SEO Strapi-side based on [RFC SV-015](https://pagopa.atlassian.net/wiki/spaces/SV/pages/931627186/SV-015+Requisiti+di+SEO)
Page:
- Added `metaTitle` (required, max length: 60)
- Added `metaDescription` (required, length between 50 and 160)
- Added `keywords` (optional)
- Added `canonicalURL` (optional)
- Added `ogTitle` (optional, max length: 60)
- Added `ogDescription` (optional, max length: 65) --> Logic here is that if you're going to fill the field you should do it optimally (with less than 65 characters), otherwise we'll default to metaDescription, which is longer (so not optimal) but better than nothing
Added `general` single type component containing:
- `metaImage` (required)
- `favicon` (required)
- `appleTouchIcon` (required)
- `manifest` (required)
`manifest` is …
=> [B2BP-392] Add SEO to Strapi

.github/actions/deploy/action.yaml
New approach to resolve issue described in PR #173  since it was unsuccessful (check PR #176 for reference)
- Removed use of NextJS cache from deploy action
- Bug resolution
To be tested in a production-like environment.
=> [B2BP-397] Removed used of NextJS cache

.changeset/grumpy-cooks-fetch.md, .changeset/old-peaches-wait.md, apps/nextjs-website/src/components/StripeLink.tsx, apps/strapi-cms/src/components/sections/stripe-link.json
- Added support for rendering subtitle using MarkdownRenderer.
- Updated styling to ensure consistency with theme.
The motivation behind this change is to enhance the StripeLink component by adding support for rendering subtitles using MarkdownRenderer. This will allow for better formatting and presentation of subtitles. Additionally, some minor styling adjustments have been made to ensure consistency with the theme.
Tested in local
=> [B2BP-400] - StripeLink HTML rendering bug fix

.changeset/khaki-geckos-drum.md, .changeset/tiny-pandas-raise.md, apps/nextjs-website/src/components/BannerLink.tsx, apps/strapi-cms/src/components/sections/banner-link.json
- Added support for rendering subtitle using MarkdownRenderer.
The motivation behind this change is to enhance the Bannerlink component by adding support for rendering body using MarkdownRenderer. This will allow for better formatting and presentation of subtitles.
Tested in local
=> [B2BP-354] - BannerLink HTML rendering

.changeset/young-icons-fetch.md, apps/nextjs-website/src/app/layout.tsx
Solves bug described in [task 455](https://pagopa.atlassian.net/browse/B2BP-455)
- Update `ThemeProvider` import
Bug fix. Could not build.
Tested locally reproducing the issue and applying the solution.
=> [B2BP-455] Fix ThemeProvider import

.github/workflows/code_review_infra.yaml, .github/workflows/deploy_cms.yaml, .github/workflows/deploy_infra.yml, .github/workflows/deploy_website.yaml
- Set concurrency to deploy_website workflow
- Set concurrency to deploy_infra workflow
- Set concurrency to deploy_cms workflow
- Set concurrency to code_review_infra workflow
We don't want the workflows are failing due to a lock conflict.
=> [B2BP-477] Set concurrency in GitHub Action workflows

.github/workflows/changelog.yaml, .github/workflows/check_pr_title.yaml, package.json
- Update some details of the PR opened by changeset
- Instruct the checkout action to also checkout the tags
We want to let changeset create the tags
=> [B2BP-482] Fix Changelog workflow

.github/CODEOWNERS
Update CODEOWNERS
We need to delegate ownership to other members of the team.
=> [B2BP-516] Update CODEOWNERS

.github/CODEOWNERS
- Update `CODEOWNERS` file
Allow to merge the PR opened by [changesets](https://github.com/changesets/changesets)
N/A
=> [B2BP-526] Update codeowners

.github/CODEOWNERS
Add @pagopa/b2bportals-maintain as owner of all the apps
Without this PR the PRs created by changesets are not mergiable by the maintainers
N/A
=> [B2BP-526] Add maintainers as codeowners of apps

.changeset/dry-hats-try.md, apps/infrastructure/src/rds_aurora.tf
**List of Changes**
Enable auto_minor_version_upgrade
Remove minor from version of the cms database
**Motivation and Context**
Without the auto_minor_version_upgrade terraform try to downgrade the version of postgre if AWS auto-update the version of postgre during the maintenance windows. (https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/286#issuecomment-1456413998)
=> [B2BP-547] - Fix downgrade rds version

.changeset/orange-ladybugs-applaud.md, apps/infrastructure/src/ecs.tf
**List of Changes**
Ignore changes on task definition
**Motivation and Context**
We don't want to downgrade the task-definition if the version from Terraform state differs after an execution of the Deploy CMS workflow
=> [B2BP-548] Terraform Fix ignore task definition change

.changeset/green-days-pay.md, apps/infrastructure/src/acm.tf, apps/infrastructure/src/main.tf, apps/infrastructure/src/variables.tf
Create SSL certificate (without validation) for cdn distribution websites.
Modify Terraform file acm.tf and variable.tf
Create SSL certificate for cdn distribtion websites
=> [B2BP-512] - Create SSL certificate for cdn websites

.changeset/tiny-laws-stare.md, apps/infrastructure/src/variables.tf
With SEND group it was decided to first carry out tests on one of their test domain "test-portal.pn.pagopa.it". This PR create SSL Certificate for Test domain SEND "test-portal.pn.pagopa.it"
Modify variable.tf terraform file
Create SSL Certificate for Test domain SEND "test-portal.pn.pagopa.it"
=> [B2BP-551] - Create SSL Certificate for Test env SEND

.changeset/popular-moose-flow.md, apps/infrastructure/src/cloudfront.tf, apps/infrastructure/src/variables.tf
Set domain production for-ssl certificate SEND and comment CDN Send for delete test send distribution
variable.tf and cloudfront.tg terraform file
Set domain production for-ssl certificate SEND and comment CDN Send
=> [B2BP-275] - Create ssl certificate for SEND Production and comment CDN

.changeset/moody-mugs-sell.md, apps/infrastructure/src/cloudfront.tf
Fix for set alias condition for CDN
cloudfront.tf terraform file
Fix for set alias condition for CDN
=> [B2BP-555] - Fix for set alias condition for CDN

.changeset/smooth-tigers-roll.md, apps/infrastructure/src/variables.tf
Add CDN for tenant appio
variables.tf terraform file
Add CDN for tenant appio
=> [B2BP-563] - Add CDN for tenant appio

.changeset/slimy-jars-sneeze.md, apps/nextjs-website/package.json, package-lock.json
Build failed due to missing dependency "@mui/lab"
Add missing dependency
Bug fix
Tested locally
=> [B2BP-588] Add @mui/lab dependency required by mui-italia

.changeset/quiet-camels-laugh.md, .github/workflows/deploy_storybook.yaml
Workflow GitHub for build and deploy NextJS Storybook on AWS S3 and CDN
Depends on #284 
create _deploy_storybook.yaml_ file
Workflow GitHub for build and deploy NextJS Storybook on AWS S3 and CDN
On GitHub test environment
=> [B2BP-605] - Workflow GitHub Storybook

.github/workflows/deploy_storybook.yaml
Update workflow github for deploy a Storybook by modify working directory position.
This update resolve the NPM error in "Install dependencies" step.
deploy_storybook.yaml
Update workflow github for deploy a Storybook by modify working directory position
on test environment
=> [B2BP-605] - Modify workflow github Storybook

.changeset/odd-waves-study.md, apps/nextjs-website/react-components/components/common/Common.helpers.ts, apps/nextjs-website/src/app/theme.ts
- Fixed buttons colour palette colour schema
This PR is made to align components to the legacy version of SEND
Tested locally
=> [B2BP-624] - Fix Buttons style

.changeset/light-llamas-tap.md, apps/infrastructure/src/cloudfront.tf
Add cname CDN Storybook
cloudfront.tf
Add cname CDN Storybook
=> [B2BP-614] - Add cname CDN Storybook

.changeset/angry-moose-act.md, apps/infrastructure/src/variables.tf
Add Tenant "demo" on AWS (CDN and folder S3).
For this tenant is not expected the use of a custom domain and a certificate. For this reason, the tenant URL is set to a fictitious "demo.b2bportals.pagopa.it"
terraform file variables.tf
Add Tenant "demo" on AWS (CDN and folder S3)
=> [B2BP-631] - Terraform Add Tenant demo

.github/workflows/deploy_website.yaml
Add tenant "demo" in workflow GitHub "deploy_website".
deploy_website.yaml file
Add tenant "demo" in workflow GitHub "deploy_website".
=> [B2BP-632] - Workflow GitHub add tenant demo

.github/workflows/deploy_nextjs.yaml, apps/nextjs-website/.dockerignore, apps/nextjs-website/Dockerfile
Workflow GitHub for Deploy NextJS in ECS Fargate on AWS for Strapi Preview
Create deploy_nextjs.yaml file and Dockerfile
Workflow GitHub for Deploy NextJS in ECS Fargate on AWS for Strapi Preview
=> [B2BP-650] - Workflow GitHub Deploy NextJS on AWS

.changeset/chilly-games-run.md, apps/nextjs-website/react-components/components/PreHeader/PreHeader.tsx
- Fixed PreHeader layout
Before Fix
After Fix
This PR is made to align components to the legacy version of SEND
Tested locally
=> [B2BP-654] - Fix style PreHeader

.changeset/odd-apples-smoke.md, apps/infrastructure/src/cloudwatch_logs.tf, apps/infrastructure/src/iam_policy.tf, apps/infrastructure/src/iam_role.tf, apps/infrastructure/src/task-definitions/cms_app.json.tpl, apps/infrastructure/src/task-definitions/nextjs_app.json.tpl
Add logs to ECS
Add logs to ECS
Add logs to ECS
=> [B2BP-649] - Add logs to ECS

.changeset/shy-kangaroos-type.md, apps/infrastructure/src/task-definitions/cms_app.json.tpl, apps/infrastructure/src/task-definitions/nextjs_app.json.tpl
Add stream prefix to ECS logs
Add stream prefix to ECS logs
Add stream prefix to ECS logs
=> [B2BP-649] - Add stream prefix to ECS logs

.changeset/strange-kangaroos-accept.md, apps/infrastructure/src/ecs.tf, apps/infrastructure/src/iam_policy.tf, apps/infrastructure/src/ssm_parameter.tf, apps/infrastructure/src/task-definitions/nextjs_app.json.tpl
Modify ECS env var NextJS
Modify ECS env var NextJS
Modify ECS env var NextJS
=> [B2BP-649] - Modify ECS env var NextJS

.changeset/proud-books-leave.md, apps/nextjs-website/react-components/components/Accordion/Accordion.tsx
- Fixed Accordion layout
Before Fix
After Fix
This PR is made to align components to the legacy version of SEND
Tested locally
=> [B2BP-658] - Fix style Accordion

.changeset/tall-jeans-yell.md, apps/infrastructure/src/cloudfront.tf, apps/infrastructure/src/iam_policy.tf, apps/infrastructure/src/s3_bucket.tf
Add S3, policy IAM and CDN for Medialibrary multitenant
Terraform files
Add S3, policy IAM and CDN for Medialibrary multitenant
=> [B2BP-669] - Add S3 and CDN Medialibrary multitenant

.changeset/chilled-berries-divide.md, apps/infrastructure/src/alb.tf, apps/infrastructure/src/ecs.tf, apps/infrastructure/src/ssm_parameter.tf
Add ECS service, task definition and target group for Strapi Multitenant
Depends on #322 
Terraform files
Add ECS service, task definition and target group for Strapi Multitenant
=> [B2BP-670] - ECS and TargetGroup for Strapi Multitenant

apps/infrastructure/src/acm.tf, apps/infrastructure/src/alb.tf, apps/infrastructure/src/route_53.tf
Add AWS ACM ALB Route53 for Strapi Multitenant
Depends on #323 
Terraform files
Add AWS ACM ALB Route53 for Strapi Multitenant
=> [B2BP-671] - Add AWS ACM ALB Route53 Multitenant

.changeset/khaki-pants-carry.md, apps/nextjs-website/react-components/components/Editorial-Switch/Editorial-Switch.tsx, apps/nextjs-website/react-components/types/Editorial-Switch/Editorial-Switch.types.ts, apps/nextjs-website/stories/Editorial-Switch/dark.stories.tsx, apps/nextjs-website/stories/Editorial-Switch/editorialCommons.tsx, apps/nextjs-website/stories/Editorial-Switch/light.stories.tsx
- Fixed Editorial-Switch while using the storybook
This PR is made to fix the issue about rendering the component while using the Storybook
Tested locally
=> [B2BP-667] - Fix Editorial-Switch Storybook error

.github/workflows/deploy_website.yaml
Remove trigger on merge PR in Workflow DeployWebsite 
deploy_website.yaml file
Remove trigger on merge PR in Workflow DeployWebsite
=> [B2BP-673] - Workflow DeployWebsite Remove trigger on merge PR

.changeset/dry-crews-eat.md, apps/nextjs-website/stories/Hero/heroCommons.tsx
- Fixed Hero Storybook Light background color
This PR is made to fix the issue about rendering the component while using the Storybook
Tested locally
=> [B2BP-690] - Fix Hero Storybook Light Version

.changeset/lovely-beds-attack.md, apps/infrastructure/src/ecs.tf, apps/infrastructure/src/task-definitions/cms_app.json.tpl
Set DB schema ECS Strapi with Tenant name
ecs.tf file
Set DB schema ECS Strapi with Tenant
=> [B2BP-703] - Set DB schema ECS Strapi with Tenant

.github/actions/deploy/action.yaml, .github/workflows/deploy_website.yaml
Add var "Strapi_URL" and "Strapi_token" for workflow and action deploy website
Workflow and action deploy WebSite
Add var "Strapi_URL" and "Strapi_token" for workflow and action deploy website
=> [B2BP-704] - Add var strapi for deploy website

.github/workflows/deploy_storybook.yaml
Modify trigger condition for Workflow Storybook
Workflow triggered for Push on  'apps/nextjs-website/**' path
Modify trigger condition for Workflow Storybook
=> [B2BP-710] - Workflow Storybook modify trigger condition

.changeset/gentle-rice-thank.md, apps/nextjs-website/react-components/components/Form/Form.tsx, apps/nextjs-website/react-components/types/Form/Form.types.ts, apps/nextjs-website/stories/Form/formCommons.tsx
- Fixed Form on storybook
This PR will delete unusued elements on storybook
Tested locally
=> [B2BP-715] - Update Form Storybook

.changeset/fluffy-geckos-hang.md, apps/infrastructure/src/cloudwatch_dashboard.tf, apps/infrastructure/src/cloudwatch_metric_alarm.tf
Modify CloudWatch Metrics and Dashboard for remove old Strapi and add new Strapi
Cloudwatch Metrics and Dashboards
Modify CloudWatch Metrics and Dashboard for remove old Strapi and add new Strapi
=> [B2BP-747] - Modify CloudWatch from old to new Strapi

.changeset/fluffy-parrots-allow.md, apps/infrastructure/src/variables.tf
Add resources on AWS for Tenant "Firma"
variables.tf file
Add resources on AWS for Tenant "Firma"
=> [B2BP-772] - Add Firma Tenant on AWS

.github/workflows/deploy_cms.yaml
Add tenant "firma" in Workflow deploy cms
Add tenant "firma" in Workflow deploy cms
Add tenant "firma" in Workflow deploy cms
=> [B2BP-772] - Workflow deploy cms add tenant firma

.changeset/slow-waves-compete.md, apps/nextjs-website/src/components/BannerLink.tsx
- Fix 'Use Client' request on build failure
This PR is made in order to fix the build error about "Use Client"
The generated HTML equates the old one.
=> [B2BP-745] - Fix UseClient error on BannerLink

.changeset/breezy-seas-wash.md, .github/workflows/deploy_cms.yaml, apps/infrastructure/src/variables.tf
Add Tenant PDND on AWS and in WorkFlow Deploy CMS
Add Tenant PDND on AWS and in WorkFlow Deploy CMS
Add Tenant PDND on AWS and in WorkFlow Deploy CMS
=> [B2BP-773] - Add Tenant PDND on AWS

.changeset/quiet-games-help.md, .github/workflows/deploy_cms.yaml, apps/infrastructure/src/variables.tf
Add Tenant "interop" on AWS and in Workflow Deploy_CMS
Add Tenant "interop" on AWS and in Workflow Deploy_CMS
Add Tenant "interop" on AWS and in Workflow Deploy_CMS
=> [B2BP-785] - AWS add Tenant interop

.changeset/ten-jobs-collect.md, apps/nextjs-website/react-components/components/HeroCounter/HeroCounter.tsx
- Changed text alignment for counter and counter text to be centered
- Changed font size for the counter on mobile
- Changed font size for the title on mobile
This PR implement the possibility to upload one image for the desktop and another one for mobile responsive.
Tested locally
=> [B2BP-696] Fix Hero Counter style

.changeset/chilly-hotels-pull.md, .changeset/tricky-weeks-destroy.md, apps/nextjs-website/package.json, apps/nextjs-website/react-components/components/Form/Form.helpers.tsx, apps/nextjs-website/react-components/components/Form/Form.tsx, apps/nextjs-website/react-components/types/Form/Form.types.ts, apps/nextjs-website/src/components/Form.tsx, apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts, apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts, apps/nextjs-website/src/lib/fetch/navigation.ts, apps/nextjs-website/src/lib/fetch/preview.ts, apps/nextjs-website/src/lib/fetch/types/PageSection.ts, apps/nextjs-website/stories/Form/formCommons.tsx, apps/strapi-cms/src/api/page/content-types/page/schema.json, apps/strapi-cms/src/components/components/form-category.json, apps/strapi-cms/src/components/sections/form.json, package-lock.json
The Form component. while graphically complete, was missing all data logic.
This PR implements the data logic, the call to the newsletter service the Form is supposed to call and adds the working section to Strapi.
- Update props to reflect data requested by the newsletter service
- Refactor Form based on new data shape
- Implement ReCaptcha
- Implement call to newsletter service
- Add Form section to Strapi
- Updated population parameters to include Form's `categories` field
Add working Form component
Strapi-NextJS connection and the rendering of the component fully tested.
Needs to be tested with official data to verify both ReCaptcha and the call to the newsletter service.
=> [B2BP-715] Refactor Form component and add it to Strapi

.changeset/selfish-toys-laugh.md, apps/nextjs-website/react-components/components/VideoImage/VideoImage.helpers.tsx, apps/nextjs-website/react-components/components/VideoImage/VideoImage.tsx
- Fix the issue for the responsive version
This PR is made to change the behaviour of the responsive version (mobile) to align it with the design.
Tested locally
=> [B2BP-840] - VideoImage component responsive fix

apps/infrastructure/src/cloudwatch_metric_alarm.tf, apps/infrastructure/src/sns.tf
- Added SNS topic for alarms
- Set alarm actions on all cloudwatch alarms to send notifications to SNS
Cloudwatch alarms have been put in place, but no notification is sent proactively.
This PR will allow the stakeholders to receive an email and/or a slack message
=> [B2BP-438] Notify emails on cloudwatch alarms

apps/infrastructure/src/ecs.tf
Refactored datasource template_file to function templatefile
The template_file datasource is not longer maintained and not supported by arm64 architectures (as Mac M1/M2)
=> [B2BP-874] - Refactored datasource template_file to function templatefile

.changeset/twenty-plums-teach.md, apps/nextjs-website/react-components/components/VideoImage/VideoImage.tsx
- Fix window.innerWidth build error
This PR is made to fix the error on production for the window.innerWidth code on the VideoImage component
Tested locally
=> [B2BP-883] - VideoImage bug fix

.changeset/gorgeous-news-move.md, .changeset/short-baboons-notice.md, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx, apps/strapi-cms/src/components/sections/hero.json
As per title.
- Add Link to Strapi's Hero section
- Separate Link from StoreButtons in NextJS
Updated requirements.
Ran locally in dev and storybook.
=> [B2BP-851] Add tertiary link to Hero section in Strapi

.changeset/ten-chairs-suffer.md, apps/strapi-cms/src/api/page/content-types/page/schema.json, package-lock.json
As per title.
Note:
This is a workaround to a quirk in Strapi.
If approved, it will introduce the possibility to create multiple pages with the same slug.
While less than ideal, the issue is not breaking, since all NextJS will do is render all pages with the same slug in order of appearance and overwrite the previous one in the chain.
This means that the static generation of the website will end with the slug in question being populated with the most recent page. This does NOT currently raise any error (which imo is not a desirable behaviour) and just silently "deletes" all pages with the same slug but one (the newest).
- Unchecked "unique" attribute of `slug` field of `Page`
One of the latest Strapi updates introduced the bug in question.
Before, cloning an entity opened a new page in …
=> [B2BP-893] Remove slug's "unique"ness to allow cloning pages

.github/CODEOWNERS
As per title.
Update CODEOWNERS file to reflect change in team structure.
- Updated CODEOWNERS file substituing `Meolocious` with `salvatorediocaro`
salvatorediocaro is now responsible for reviewing and creating PRs directly
Not tested.
=> [B2BP-896] Substitute Meolocious for salvatorediocaro in CODEOWNERS file

.changeset/shaggy-rats-drop.md, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx
Change padding and width of hero small
Change component style
BEFORE
AFTER
=> [B2BP-901] - Hero small style fix

.changeset/cool-queens-count.md, apps/strapi-cms/src/components/menu/mega-menu-link.json
As per title.
As per title.
User requested change.
Ran locally.
=> [B2BP-923] Increase MegaHeader sublink groups limit to 4

package-lock.json
Deploy Website currently fails with an "Invalid package lock" error.
This PR updates the package-lock to solve the issue.
- Update package-lock
Bug fix
To be tested by seeing if deploy works.
=> Fix static site build fail

.changeset/sharp-rockets-camp.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
As per title.
- Surrounded unstyled links with a Typography component using the HTML component it substituted
Graphical bug fix
Ran locally using prod data.
=> [B2BP-903] Fix styling of MegaHeader links

.changeset/breezy-carrots-nail.md, apps/nextjs-website/react-components/components/Feature/Subtitle.tsx, apps/nextjs-website/react-components/components/HowTo/HowTo.tsx
Change font style of Feature and HowTo components
Modify style
Run locally on localhost:3000 and localhost:6006
=> [B2BP-902] - Fix font of feature and howto components

.changeset/purple-jobs-share.md, apps/nextjs-website/react-components/components/Cards/Cards.tsx, apps/nextjs-website/react-components/components/Cards/CardsItem.tsx
- Change font size
- Remove letters capitalization 
Change style
=> [B2BP-927] [B2BP-928] - Fix cards component font

.changeset/tall-geckos-return.md, apps/nextjs-website/react-components/components/Editorial/Editorial.tsx
Change Editorial UI
Change component style
Run on localhost:3000 or localhost:6006
BEFORE
AFTER
=> [B2BP-907] - Editorial: change image text order on mobile breakpoint

.changeset/clean-snails-lick.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.Helpers.ts, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
Fix bug for which the MegaHeader's menu would scroll with the page instead of sticking to the top.
Also, fix styling of MegaHeader's Mobile Menu.
- Bring everything inside Container
- Make Menu positioning relative to Header (Container), making it stick to the top of the page with it
- Add Styling to Mobile Menu
Bug fix
Ran locally.
=> [B2BP-936] [B2BP-945] Megaheader Style Fix

apps/nextjs-website/stories/HighlightBox/default.stories.tsx
As per title.
As per title.
Bug fix: Missing types prevented NextJS from building.
Problem doesn't exist in dev.
=> Add types to HighlightBox stories

.changeset/happy-eggs-design.md, apps/nextjs-website/src/components/PageSwitch.tsx
As per title.
- Added 'use client' to PageSwitch
Bug fix
=> [B2BP-958] Bug fix: Deploy failed due to missing 'use client' in PageSwitch

.changeset/kind-jokes-train.md, apps/nextjs-website/react-components/components/Cards/Cards.tsx, apps/nextjs-website/react-components/components/Cards/CardsItem.tsx
- Change minimum height of cards
- Change text spacing
Style fix
BEFORE
AFTER
=> [B2BP-930] - Cards: define minimum height of the items

.changeset/lemon-spiders-battle.md, .changeset/strong-needles-build.md, apps/nextjs-website/react-components/components/StripeLink/StripeLink.tsx, apps/nextjs-website/react-components/types/StripeLink/StripeLink.types.ts, apps/nextjs-website/src/components/StripeLink.tsx, apps/nextjs-website/src/lib/fetch/__tests__/navigation.test.ts, apps/nextjs-website/src/lib/fetch/types/PageSection.ts, apps/nextjs-website/stories/StripeLink/dark.stories.tsx, apps/nextjs-website/stories/StripeLink/light.stories.tsx, apps/nextjs-website/stories/StripeLink/stripelinkCommons.tsx, apps/strapi-cms/src/components/sections/stripe-link.json
Add link field to Stripelink in Nextjs
=> [B2BP-972] - Nextjs stripelink add link

.changeset/great-eyes-explain.md, apps/nextjs-website/react-components/components/FramedVideo/FramedVideo.helpers.tsx, apps/nextjs-website/react-components/components/FramedVideo/FramedVideo.tsx
- Change background color in dark mode
- Change text alignment in mobile mode
- Change video width 
Fix bugs
BEFORE 
AFTER
=> [B2BP-970] - Fix framed video bugs

.changeset/wise-actors-marry.md, apps/nextjs-website/react-components/components/BannerLink/BannerLink.tsx
- Fix mobile display bugs
- Change body text color in dark mode
Fix bugs
BEFORE
AFTER
=> [B2BP-971] [B2BP-960] - BannerLink : fix mobile display bugs and change text color

.changeset/calm-chicken-marry.md, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx, apps/nextjs-website/react-components/components/Hero/Hero.tsx
Same as the title 
Fix bug
Run locally on localhost:3000 or localhost6006
BEFORE
AFTER
=> [B2BP-979] - Change Hero component spacing

.changeset/silly-donkeys-vanish.md, apps/nextjs-website/src/components/Icon.tsx, apps/nextjs-website/src/lib/fetch/types/icons/SocialIcon.ts, apps/strapi-cms/src/components/components/footer-link-social.json
=> [B2BP-922] Add YouTube as a valid icon for Footer Social Links

.changeset/short-badgers-kick.md, apps/nextjs-website/react-components/components/FramedVideo/FramedVideo.tsx, apps/nextjs-website/react-components/types/FramedVideo/FramedVideo.types.ts, apps/nextjs-website/src/components/FramedVideo.tsx, apps/nextjs-website/src/lib/fetch/types/PageSection.ts, apps/nextjs-website/stories/FramedVideo/framedVideoCommons.tsx, apps/strapi-cms/src/components/sections/framed-video.json
As per title
Ran locally in dev and preview
=> [B2BP-988] [B2BP-989] Add loop and autoplay to FramedVideo

.changeset/rich-tigers-build.md, apps/nextjs-website/react-components/components/Form/Form.tsx, apps/nextjs-website/react-components/types/Form/Form.types.ts, apps/nextjs-website/src/components/Form.tsx, apps/nextjs-website/src/lib/fetch/types/PageSection.ts
Add background image to form in NextJS
Run locally on locahost:6006
BEFORE 
AFTER
=> [B2BP-983] - Form : Add background image

.changeset/soft-moons-rescue.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.Helpers.ts, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
- Change font
- Change  box-shadow
- Change spacing 
- Change page scrolling
=> [B2BP-973] - Megaheader: style refinement

.changeset/poor-ligers-doubt.md, apps/nextjs-website/react-components/components/HighlightBox/HighlightBox.tsx, apps/nextjs-website/stories/HighlightBox/default.stories.tsx
=> [B2BP-986] -  Highlight Box: remove button shade in the no-button version

.changeset/cool-sloths-double.md, apps/nextjs-website/react-components/components/BannerLink/BannerLink.tsx, apps/nextjs-website/react-components/components/Cards/Cards.tsx, apps/nextjs-website/react-components/components/Editorial/Ctas.tsx, apps/nextjs-website/react-components/components/Form/Form.tsx, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx, apps/nextjs-website/react-components/components/PreFooter/PreFooter.tsx, apps/nextjs-website/src/app/theme.ts
Change button color in editorial, cards, hero, bannerlink, prefooter and form components
Update style 
BEFORE
AFTER
=> [B2BP-908] -  Editorial : change color of the buttons

apps/infrastructure/src/variables.tf
Creation of the SSL certificate for the firma con io website enabled
Firma con io website is going to be published via PAWSBuilder soon
=> [B2BP-990] - Create firma certificate

apps/infrastructure/src/variables.tf
=> [B2BP-990] - Fix Firma url_tenant value

apps/infrastructure/src/variables.tf
Firma con io certificate has been validated and can be now used
Firma con io website is going to be published via PAWSBuilder soon
=> [B2BP-990] - Make CDN use firma certificate

apps/infrastructure/src/variables.tf
=> [B2BP-990] - Enable alias on firma cdn

.changeset/friendly-cameras-confess.md, apps/nextjs-website/react-components/components/RowText/RowText.tsx, apps/nextjs-website/react-components/types/RowText/RowText.types.ts, apps/nextjs-website/src/components/RowText.tsx, apps/nextjs-website/src/lib/fetch/types/PageSection.ts, apps/nextjs-website/stories/RowText/rowTextCommons.tsx
=> [B2BP-993] - RowText: Enable rich-text in component body

.changeset/great-beds-hear.md, apps/nextjs-website/package.json, package-lock.json
Update dependencies
Test in production
=> [B2BP-998] - Update iframe-resizer version

.changeset/thirty-carrots-talk.md, apps/nextjs-website/react-components/components/VideoImage/VideoImage.helpers.tsx, apps/nextjs-website/react-components/components/VideoImage/VideoImage.tsx
=> [B2BP-1007] - VideoImage: fine-tuning

.changeset/odd-nails-kiss.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
=> [B2BP-1054] MegaHeader - enable close on click/tap out

.changeset/loud-turtles-taste.md, apps/nextjs-website/react-components/components/Hero/Hero.tsx
Same as the title 
Run locally on locahost:3000 or localhost:6006
=> [B2BP-1052] - Hero : remove margin-y from images

.changeset/spicy-windows-kneel.md, apps/nextjs-website/react-components/components/PreFooter/PreFooter.tsx
=> [B2BP-1053] - Prefooter : change store buttons direction

.changeset/serious-lobsters-hope.md, apps/nextjs-website/stories/PressReleaseList/default.stories.tsx
As per title.
The lack of explicit types made the static website build fail.
As per title.
Bug Fix
Ran build locally
=> [B2BP-1070] Add explicit types to PressReleaseList stories

.changeset/flat-readers-float.md, apps/nextjs-website/react-components/components/MediaResources/MediaResources.tsx, apps/nextjs-website/react-components/components/index.ts, apps/nextjs-website/react-components/types/MediaResources/MediaResources.types.ts, apps/nextjs-website/react-components/types/index.ts, apps/nextjs-website/src/components/MediaResources.tsx, apps/nextjs-website/src/components/PageSection/PageSection.tsx, apps/nextjs-website/src/lib/fetch/types/PageSection.ts, apps/nextjs-website/stories/MediaResources/default.stories.tsx
=> [B2BP-1063] - NextJS : Add MediaResources component

.changeset/unlucky-keys-promise.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
=> [B2BP-1069] - MegaHeader : Make logo clickable

.changeset/beige-rice-travel.md, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx, apps/nextjs-website/react-components/components/Hero/Hero.tsx
=> [B2BP-1071] - Hero : remove margin from texts

.changeset/fair-buses-draw.md, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx
=> [B2BP-1074] - Hero : Add blank target to store buttons

.changeset/silly-experts-sin.md, apps/nextjs-website/react-components/components/PressReleaseList/PressReleaseList.tsx
=> [B2BP-1072] - PressReleaseList : Add margin-y

.changeset/famous-deers-glow.md, apps/nextjs-website/react-components/components/ServiceCarousel/ServiceCarousel.tsx
=> [B2BP-1076] - Service Carousel : add endless scrolling

.changeset/sharp-weeks-report.md, apps/strapi-cms/src/components/sections/video-image.json
=> [B2BP-1094] Strapi: Make VideoImage's subtitle RichText

.changeset/slow-hotels-share.md, apps/nextjs-website/react-components/components/VideoImage/VideoImage.helpers.tsx, apps/nextjs-website/react-components/components/VideoImage/VideoImage.tsx, apps/nextjs-website/react-components/types/VideoImage/VideoImage.types.ts, apps/nextjs-website/src/components/VideoImage.tsx, apps/nextjs-website/stories/VideoImage/dark.stories.tsx
=> [B2BP-1078] - NextJS: Make VideoImage's subtitle RichText

.github/workflows/deploy_cms.yaml, .github/workflows/deploy_nextjs.yaml
=> [B2BP-1105] Fix CMS deploy github action

.changeset/mean-roses-remember.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
=> [B2BP-1089] - Fix megaheader closing when clicking on anchored link

.changeset/dirty-jars-argue.md, apps/nextjs-website/react-components/components/Form/Form.helpers.tsx
=> [B2BP-1101] - Form: fix radio buttons alignment

apps/nextjs-website/Dockerfile
=> feat: update docker image strapi-cms

apps/nextjs-website/Dockerfile, apps/strapi-cms/Dockerfile
=> fix: nextjs-website docker image version and strapi

.changeset/gorgeous-files-deny.md, apps/nextjs-website/react-components/components/PressRelease/PressRelease.tsx, apps/nextjs-website/react-components/components/PressReleaseList/PressReleaseList.tsx, apps/nextjs-website/src/components/PressReleaseList.tsx, apps/nextjs-website/stories/PressReleaseList/default.stories.tsx
=> [B2BP-1086] [B2BP-1088] - Press Release: switch to european date notation and add margins to title

.changeset/seven-berries-pump.md, apps/strapi-cms/config/plugins.ts, apps/strapi-cms/package.json, package-lock.json
As per title.
- Updated provider version
- Moved credentials configuration in a deeper level [as per docs](https://www.npmjs.com/package/@strapi/provider-upload-aws-s3#provider-configuration)
Fix Bug: Unable to upload assets to Media Library after migration to Strapi V5
=> Bug Fix: Upgrade AWS S3 provider version and configuration

.changeset/slimy-bobcats-nail.md, apps/nextjs-website/next.config.js
Follows PR #555 and further ups timeout to allow for 4 and 5 languages.
=> Bug Fix: Up SSG timeout to 10 minutes

.changeset/hip-bottles-heal.md, apps/nextjs-website/react-components/components/Header/helpers/Header.Card.helpers.tsx
=> [B2BP-1144] - Header: change the layout of the cards

.changeset/gorgeous-lions-drum.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
=> [B2BP-1137] - Megaheader: fix bugs on mobile scroll

apps/infrastructure/src/variables.tf
=> [B2BP-1166] Setup appio.it for production switch

apps/infrastructure/src/.terraform.lock.hcl, apps/infrastructure/src/variables.tf
=> Use dev.notifichedigitali.net as alias for send tenant

.changeset/chilled-weeks-rhyme.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx
=> Bug fix: MegaHeader AppCTAButton takes priority even if undefined

apps/nextjs-website/react-components/components/PreFooter/PreFooter.tsx
As per title.
Corrected imports
Bug Fix
=> [B2BP-1178] Bug Fix: Apple Store buttons show Google Play image

.changeset/cuddly-queens-dream.md, apps/nextjs-website/src/components/ConsentHandler.tsx, apps/nextjs-website/src/components/TrackPageView.tsx
As per title
Legal Requirement
=> [B2BP-1179] Initialize MixPanel only after consent has been given

.changeset/tricky-donuts-sell.md, apps/nextjs-website/react-components/components/VideoImage/VideoImage.helpers.tsx, apps/nextjs-website/react-components/components/VideoImage/VideoImage.tsx
=> [B2BP-1162] - VideoImage: change mobile image width

.changeset/shaggy-spies-sit.md, apps/nextjs-website/react-components/components/Accordion/Accordion.tsx, apps/nextjs-website/react-components/components/Accordion/AccordionItem.tsx, apps/nextjs-website/react-components/types/Accordion/Accordion.types.ts, apps/nextjs-website/src/components/Accordion.tsx, apps/nextjs-website/src/lib/fetch/types/PageSection.ts
As per title.
- Add trackItemOpen field
- Track accordion item opening calling mixpanel.track with event name "FAQ" and property "FAQ Name" set to the accordion item's ID
=> [B2BP-1182] Track FAQ opening with mixpanel

.changeset/gorgeous-candles-chew.md, apps/nextjs-website/src/components/OneTrust.tsx
=> [B2BP-1184] - OneTrust: add margin bottom

.changeset/real-seahorses-rush.md, apps/nextjs-website/src/app/[[...slug]]/layout.tsx
As per title.
Request by legal to reduce possible number of cookies.
Ran locally in dev.
=> [B2BP-1172] Add global properties to make ReCaptcha use recaptcha.net instead of google.com

.changeset/wicked-ears-cheat.md, apps/nextjs-website/react-components/components/Editorial/Ctas.tsx, apps/nextjs-website/react-components/components/Hero/Hero.helpers.tsx, apps/nextjs-website/react-components/components/PreFooter/PreFooter.tsx, apps/nextjs-website/react-components/components/common/StoreButtons.tsx
As per title.
- Created reusable components for store buttons (GooglePlayButton and AppStoreButton)
- Converted all use of storeButtons (PreFooter, Hero, Editorial) to newly created components
- Added onClick function to track respective click events before page change
Feature Request (appio only)
Ran locally in dev fetching from appio's online Strapi instance.
Ran locally in storybook.
=> [B2BP-1097] [B2BP-1098] [B2BP-1191] Mixpanel: Track store buttons click

.changeset/nervous-rats-own.md, apps/nextjs-website/src/AppEnv.ts
As per title.
DX (Developer Experience)
Ran locally in dev and prod
=> [B2BP-485] NextJS: Disable cache during data fetching in development

.changeset/shiny-onions-peel.md, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.Helpers.tsx, apps/nextjs-website/react-components/components/MegaHeader/MegaHeader.tsx, apps/nextjs-website/react-components/components/common/Common.tsx, apps/nextjs-website/react-components/components/common/StoreButtons.tsx, apps/nextjs-website/react-components/components/common/tracking.tsx
As per title.
- Created useMixpanelTracking hook to be used to track clicks on links or buttons
- Used hook to track MegaHeader links
- Used hook to track MegaHeader CTA
- Used hook to track storeButtons
More reliable tracking of MegaHeader.
Refactor code to keep it clean / organized.
Ran locally in dev fetching from online Strapi instance of appio.
=> [B2BP-1212] Refactored Mixpanel tracking into useMixpanelTracking hook

apps/infrastructure/src/variables.tf
=> Setup SEND prod CDN and cert

.changeset/eleven-trainers-build.md, apps/nextjs-website/package.json, apps/nextjs-website/scripts/postbuild.js, apps/nextjs-website/src/app/robots.ts
As per title.
- Add postbuild script and respective cmd in package.json
- Update build cmd in package.json to run postbuild script before finishing
- Remove /preview from robots.txt's disallow (not needed anymore)
Cleaner build
Built locally
=> [B2BP-657] Add postbuild script to remove preview page from static website build

.changeset/long-keys-brush.md, apps/nextjs-website/src/app/layout.tsx, apps/nextjs-website/src/app/not-found.tsx
As per title.
- Add html and body tags to RootLayout (fixes hydration bug)
- Add redirect logic to 404 page (taking locales into consideration)
Bug Fix + Feature Request / Website Visitor UX
Built locally fetching from SEND's online Strapi instance and served locally to replicate and fix the error and test the redirection behaviour.
=> [B2BP-1217] Fix 404 hydration error and add redirect logic to 404 page

.changeset/dry-cooks-jog.md, apps/infrastructure/src/variables.tf, apps/nextjs-website/react-components/components/Accordion/AccordionItem.tsx
=> [B2BP-1207] - Accordion: Change behavior of anchor links

.changeset/grumpy-feet-smell.md, apps/nextjs-website/src/app/preview/page.tsx, apps/nextjs-website/src/lib/api.ts, apps/nextjs-website/src/lib/fetch/__tests__/preview.test.ts, apps/nextjs-website/src/lib/fetch/preview.ts, apps/strapi-cms/config/plugins.ts
As per title.
Better CMS UX
Ran locally in preview
=> [B2BP-1214] Extend preview functionality to PageSwitch CollectionType

.changeset/hot-horses-worry.md, apps/nextjs-website/package.json, package-lock.json
As per title
Make clean script available in case of need + Uniformity among repos' scripts
Ran locally
=> [B2BP-203] Add clean script to NextJS

apps/nextjs-website/src/components/ConsentHandler.tsx, apps/nextjs-website/src/lib/__tests__/header.test.ts, apps/nextjs-website/src/lib/__tests__/image.test.ts, apps/nextjs-website/src/lib/__tests__/pressRelease.test.ts, apps/nextjs-website/src/lib/fetch/__tests__/extractFromResponse.test.ts, apps/nextjs-website/src/lib/fetch/__tests__/tenantApiData.test.ts, apps/nextjs-website/src/lib/fetch/preHeader.ts, apps/nextjs-website/src/lib/fetch/tenantApiData.ts, apps/nextjs-website/src/lib/linkLocalization.ts, apps/nextjs-website/src/lib/oneTrust.ts
As per title.
- Cover all possible lines (100% in this case) of tested files
- Add tests for untested files
Best Practice + Maintainability
Ran tests locally
=> [B2BP-1229] Maximize NextJS test coverage

.changeset/fuzzy-flowers-wonder.md, apps/nextjs-website/.storybook/preview.tsx, apps/nextjs-website/stories/Header/component.tsx, apps/nextjs-website/stories/Header/light.stories.tsx
Optimize Storybook controls for standard Header component
- Make controls more user friendly for non-technical users
- Prevent users being able to "break" the component
- Showcase what the component is capable of as extensively as possible
Better Storybook UX --> Give a better idea to CMS users of what the Header will look like in production
Ran Storybook locally
=> [B2BP-1238] Storybook: User friendly controls for Header

apps/infrastructure/src/iam_group.tf, apps/infrastructure/src/iam_policy.tf, apps/infrastructure/src/iam_user.tf
=> Add SES permissions to Strapi user

.changeset/wise-cheetahs-worry.md, apps/strapi-cms/package.json, package-lock.json
=> [B2BP-1226] Strapi Plugin Deploy: Upgrade to add confirmation dialog before trigger

.changeset/gorgeous-panthers-worry.md, apps/strapi-cms/package.json, package-lock.json
Better CMS UX.
Easier troubleshooting on deployment fail.
=> [B2BP-1227] Strapi Plugin Deploy: Update to add link to workflow run's github page

.changeset/five-ads-suffer.md, apps/nextjs-website/src/components/ConsentHandler.tsx, apps/nextjs-website/src/lib/fetch/siteWideSEO.ts, apps/strapi-cms/src/components/shared/analytics.json
=> [B2BP-1215] Remove Matomo

apps/nextjs-website/react-components/components/NotFoundPage/NotFoundPage.tsx
=> [B2BP-1251] - Update NotFoundPage texts

.changeset/soft-students-breathe.md, apps/infrastructure/src/cloudfront.tf, apps/infrastructure/src/variables.tf
Allow to set cloudfront custom headers and CSP per-tenant
IO App website needed a custom CSP
=> Add possibility to set custom CSP and headers per tenant

.changeset/olive-hounds-refuse.md, apps/strapi-cms/config/plugins.ts, apps/strapi-cms/package.json, package-lock.json
As per title
Allow CMS users to autonomously reset their lost password.
Has to be tested in production AWS environment.
=> [B2BP-879] Setup Amazon SES for Strapi password recovery

.changeset/sour-penguins-return.md, apps/strapi-cms/config/admin.ts
As per title.
Verify if it's possible to update the admin's forgot password email template from simple configuration.
=> [B2BP-879] Test: Update forgotPassword email template

apps/infrastructure/src/ecs.tf, apps/infrastructure/src/task-definitions/cms_app.json.tpl
=> Add ADMIN_PANEL_URL env variable to strapi container

apps/infrastructure/src/acm.tf, apps/infrastructure/src/cloudfront.tf, apps/infrastructure/src/iam_policy.tf, apps/infrastructure/src/route_53.tf, apps/infrastructure/src/s3_bucket.tf, apps/infrastructure/src/terraform.sh
=> [DUMMY-001] Staging website infra

apps/infrastructure/src/README.md, apps/infrastructure/src/ecs.tf, apps/infrastructure/src/task-definitions/cms_app.json.tpl
=> [B2BP-1278] Update strapi environment variables

.github/actions/deploy/action.yaml, .github/workflows/deploy_website_prod.yaml, .github/workflows/deploy_website_staging.yaml
Create two new workflows to handle new deployment flow that includes a mandatory staging step:
1. **Deploy to staging**: which runs a NextJS build and moves the result to an S3 bucket
2. **Deploy to prod**: which simply copies the staging bucket's content to the production bucket
More solid deployment flow and more complete testing capabilities for CMS users
Will be tested updated deployment plugin for Strapi
=> [B2BP-1255] Create workflows for deployment to staging and promotion to production

.github/workflows/deploy_website_prod.yaml
Add missing s3 protocol in URIs.
Add `--exact-timestamps` option to sync to keep the same options from staging.
=> [B2BP-1269] Add s3:// before bucket names

.changeset/famous-fans-fetch.md, apps/nextjs-website/react-components/components/IFrame/IFrame.tsx
=> [B2BP-1297] iFrame: Allow geolocation and clipboard-write actions

apps/nextjs-website/react-components/components/IFrame/IFrame.tsx
=> [TEMP] Allow iFrame scroll

apps/strapi-cms/package.json, package-lock.json
=> [B2BP-1276] Update Strapi Deploy Plugin to guarantee SES compatibility

apps/infrastructure/src/alb.tf, apps/infrastructure/src/ssm_parameter.tf
=> [B2BP-1312] Update alb listener security policy

apps/infrastructure/src/route_53.tf
=> Update record txt for dynamics integration

.changeset/afraid-days-learn.md, apps/nextjs-website/react-components/types/DynamicsForm/DynamicsForm.types.ts, apps/nextjs-website/src/components/DynamicsForm.tsx
Update component style
Ran locally on localhost:3000
=> [B2BP-1237] - Change DynamicsForm style

.github/workflows/deploy_storybook.yaml
Change variable name from obsolete and empty S3_BUCKET_NAME to STORYBOOK_S3_BUCKET_NAME
Bug Fix
=> [B2BP-1322] Update bucket name in deploy_storybook.yaml
